import { MockExam } from '../types';

export const MOCK_EXAMS_DATA: MockExam[] = [
  {
    id: 'exam_midterm_1',
    title: 'Đề Thi Giữa Học Kỳ 1',
    subtitle: 'Kiểm tra chuẩn kiến thức Units 1 - 5 (Global Success 4)',
    semester: 1,
    level: 'Giữa Học Kỳ 1',
    durationMinutes: 20,
    totalQuestions: 15,
    questions: [
      {
        id: 'mt1_q1',
        skill: 'listening',
        question: 'Nghe và chọn câu trả lời đúng (Bấm loa để nghe bạn Mary nói):',
        audioPrompt: "Hello, my name is Mary. I am from Australia.",
        options: ['She is from America.', 'She is from Australia.', 'She is from Viet Nam.', 'She is from Japan.'],
        correctIndex: 1,
        explanation: 'Mary nói trong bài nghe: "I am from Australia" (Mình đến từ nước Úc).',
      },
      {
        id: 'mt1_q2',
        skill: 'listening',
        question: 'Nghe và chọn giờ đúng bạn Nam thức dậy (Bấm loa để nghe):',
        audioPrompt: "I get up at six o'clock in the morning.",
        options: ['At 5:00', 'At 6:00', 'At 6:30', 'At 7:00'],
        correctIndex: 1,
        explanation: 'Nam nói: "at six o\'clock" = 6:00 sáng.',
      },
      {
        id: 'mt1_q3',
        skill: 'listening',
        question: 'Nghe và chọn khả năng của bạn Minh (Bấm loa để nghe):',
        audioPrompt: "I can ride a bike and I can swim very well.",
        options: ['Ride a bike and swim', 'Play football and sing', 'Play the piano', 'Cook and dance'],
        correctIndex: 0,
        explanation: 'Minh nói: "I can ride a bike and I can swim very well".',
      },
      {
        id: 'mt1_q4',
        skill: 'vocab',
        question: 'Chọn từ còn thiếu: "My birthday is in ______." (Tháng Mười Hai)',
        options: ['November', 'October', 'December', 'September'],
        correctIndex: 2,
        explanation: 'Tháng 12 trong tiếng Anh là "December".',
      },
      {
        id: 'mt1_q5',
        skill: 'vocab',
        question: 'Từ nào sau đây KHÔNG thuộc nhóm các thứ trong tuần?',
        options: ['Monday', 'Sunday', 'Morning', 'Thursday'],
        correctIndex: 2,
        explanation: '"Morning" là buổi sáng, còn lại là các ngày trong tuần (thứ Hai, Chủ nhật, thứ Năm).',
      },
      {
        id: 'mt1_q6',
        skill: 'vocab',
        question: 'Cụm từ "do martial arts" có nghĩa là gì?',
        options: ['Tập võ thuật', 'Đi bơi lội', 'Chơi đàn ghi-ta', 'Chạy bộ'],
        correctIndex: 0,
        explanation: '"martial arts" là môn võ thuật.',
      },
      {
        id: 'mt1_q7',
        skill: 'grammar',
        question: 'Điền vào chỗ trống: "Where ______ she from? - She is from Japan."',
        options: ['are', 'is', 'am', 'do'],
        correctIndex: 1,
        explanation: 'Chủ ngữ "she" là ngôi thứ ba số ít nên đi với to-be "is" (Where is she from?).',
      },
      {
        id: 'mt1_q8',
        skill: 'grammar',
        question: 'Chọn câu hỏi phù hợp cho câu trả lời: "It is seven fifteen."',
        options: ['What day is it today?', 'What time is it?', 'When is your birthday?', 'What can you do?'],
        correctIndex: 1,
        explanation: 'Câu trả lời về giờ giấc (7 giờ 15 phút) nên câu hỏi là "What time is it?".',
      },
      {
        id: 'mt1_q9',
        skill: 'grammar',
        question: 'Điền từ thích hợp: "What do you do ______ Sundays? - I visit my grandparents."',
        options: ['in', 'at', 'on', 'to'],
        correctIndex: 2,
        explanation: 'Đi với các ngày trong tuần chúng ta luôn sử dụng giới từ "on" (on Sundays).',
      },
      {
        id: 'mt1_q10',
        skill: 'grammar',
        question: 'Điền dạng đúng: "Can your brother ride a horse? - No, he ______."',
        options: ['can', "can't", "isn't", "doesn't"],
        correctIndex: 1,
        explanation: 'Câu trả lời phủ định cho câu hỏi "Can..." là "No, he can\'t" (cannot).',
      },
      {
        id: 'mt1_q11',
        skill: 'grammar',
        question: 'Chọn câu viết đúng ngữ pháp nhất:',
        options: [
          'What do you want to eat? - I want some chips.',
          'What does you want to eat? - I wants some chips.',
          'What do you want eat? - I want some chips.',
          'What is you want to eat? - I want some chips.',
        ],
        correctIndex: 0,
        explanation: 'Cấu trúc đúng: "What do you want to eat? - I want some chips." (Bạn muốn ăn gì? - Mình muốn một ít khoai tây chiên).',
      },
      {
        id: 'mt1_q12',
        skill: 'reading',
        passage: "Hello, my name is Linh. Today is Saturday. I do not go to school on Saturdays. In the morning, I help my mother clean the house. In the afternoon, I play badminton with my best friend Mai in the park. Mai can play badminton very well, but she cannot play the guitar. In the evening, we watch cartoons together.",
        question: 'What day is it in the passage? (Hôm nay là thứ mấy?)',
        options: ['Sunday', 'Friday', 'Saturday', 'Monday'],
        correctIndex: 2,
        explanation: 'Trong bài viết: "Today is Saturday."',
      },
      {
        id: 'mt1_q13',
        skill: 'reading',
        passage: "Hello, my name is Linh. Today is Saturday. I do not go to school on Saturdays. In the morning, I help my mother clean the house. In the afternoon, I play badminton with my best friend Mai in the park. Mai can play badminton very well, but she cannot play the guitar. In the evening, we watch cartoons together.",
        question: 'What does Linh do in the morning? (Linh làm gì vào buổi sáng?)',
        options: ['She plays badminton.', 'She helps her mother clean the house.', 'She watches cartoons.', 'She goes to school.'],
        correctIndex: 1,
        explanation: 'Trong bài viết: "In the morning, I help my mother clean the house."',
      },
      {
        id: 'mt1_q14',
        skill: 'reading',
        passage: "Hello, my name is Linh. Today is Saturday. I do not go to school on Saturdays. In the morning, I help my mother clean the house. In the afternoon, I play badminton with my best friend Mai in the park. Mai can play badminton very well, but she cannot play the guitar. In the evening, we watch cartoons together.",
        question: 'What CANNOT Mai do? (Mai không biết làm gì?)',
        options: ['Play badminton', 'Play the guitar', 'Watch cartoons', 'Help mother'],
        correctIndex: 1,
        explanation: 'Trong bài: "she cannot play the guitar" (bạn ấy không biết chơi đàn ghi-ta).',
      },
      {
        id: 'mt1_q15',
        skill: 'reading',
        passage: "Hello, my name is Linh. Today is Saturday. I do not go to school on Saturdays. In the morning, I help my mother clean the house. In the afternoon, I play badminton with my best friend Mai in the park. Mai can play badminton very well, but she cannot play the guitar. In the evening, we watch cartoons together.",
        question: 'Where do Linh and Mai play badminton?',
        options: ['At school', 'In the park', 'In the garden', 'At home'],
        correctIndex: 1,
        explanation: 'Trong bài: "in the park" (ở công viên).',
      },
    ],
  },
  {
    id: 'exam_final_1',
    title: 'Đề Thi Cuối Học Kỳ 1 (Toàn Diện)',
    subtitle: 'Đề tổng hợp 4 kỹ năng Chuẩn Bộ GD&ĐT (Starter - Unit 10)',
    semester: 1,
    level: 'Cuối Học Kỳ 1',
    durationMinutes: 25,
    totalQuestions: 20,
    questions: [
      {
        id: 'f1_q1',
        skill: 'listening',
        question: 'Nghe và chọn môn học yêu thích của bạn Nam (Bấm loa nghe):',
        audioPrompt: "My favourite subject is English because I want to be an English teacher.",
        options: ['Maths', 'Music', 'English', 'Science'],
        correctIndex: 2,
        explanation: 'Nam nói: "My favourite subject is English".',
      },
      {
        id: 'f1_q2',
        skill: 'listening',
        question: 'Nghe và chọn ngày hội thể thao diễn ra vào tháng mấy (Bấm loa nghe):',
        audioPrompt: "Our school sports day is in November.",
        options: ['In May', 'In October', 'In November', 'In December'],
        correctIndex: 2,
        explanation: 'Bài nghe nói: "Our school sports day is in November" (tháng 11).',
      },
      {
        id: 'f1_q3',
        skill: 'listening',
        question: 'Nghe và chọn nơi bạn Lucy đã ở mùa hè năm ngoái (Bấm loa nghe):',
        audioPrompt: "Last summer, I was on holiday in London with my family.",
        options: ['Tokyo', 'Sydney', 'London', 'Ha Long Bay'],
        correctIndex: 2,
        explanation: 'Lucy nói: "I was on holiday in London".',
      },
      {
        id: 'f1_q4',
        skill: 'vocab',
        question: 'Từ nào chỉ phòng máy tính trong trường học?',
        options: ['School yard', 'Computer room', 'Music room', 'School gym'],
        correctIndex: 1,
        explanation: '"Computer room" là phòng máy vi tính của trường.',
      },
      {
        id: 'f1_q5',
        skill: 'vocab',
        question: 'Chọn từ đồng nghĩa với "marvellous / great" (tuyệt vời, kỳ diệu):',
        options: ['Boring', 'Wonderful', 'Sad', 'Difficult'],
        correctIndex: 1,
        explanation: '"Wonderful" có nghĩa là tuyệt vời, kỳ diệu.',
      },
      {
        id: 'f1_q6',
        skill: 'vocab',
        question: 'Môn học "PE" trong trường là viết tắt của môn gì?',
        options: ['Mỹ thuật (Art)', 'Thể dục (Physical Education)', 'Âm nhạc (Music)', 'Tin học (IT)'],
        correctIndex: 1,
        explanation: 'PE là viết tắt của Physical Education (Môn Thể dục).',
      },
      {
        id: 'f1_q7',
        skill: 'vocab',
        question: 'Chọn từ đúng: "Tony was on the ______ last weekend. The sea was warm and blue."',
        options: ['beach', 'mountain', 'classroom', 'library'],
        correctIndex: 0,
        explanation: 'Bãi biển (beach) đi liền với "the sea was warm and blue" (biển ấm và trong xanh).',
      },
      {
        id: 'f1_q8',
        skill: 'grammar',
        question: 'Điền từ thích hợp: "How many playgrounds ______ there at your school?"',
        options: ['is', 'are', 'was', 'am'],
        correctIndex: 1,
        explanation: 'Hỏi số lượng danh từ số nhiều (playgrounds) ta dùng "How many ... are there?".',
      },
      {
        id: 'f1_q9',
        skill: 'grammar',
        question: 'Điền vào chỗ trống: "When do you have art? - I have it ______ Tuesdays and Fridays."',
        options: ['at', 'on', 'in', 'under'],
        correctIndex: 1,
        explanation: 'Dùng giới từ "on" trước các ngày trong tuần (on Tuesdays and Fridays).',
      },
      {
        id: 'f1_q10',
        skill: 'grammar',
        question: 'Chọn câu trả lời đúng cho câu hỏi: "Why do you like music?"',
        options: [
          'Because I want to be a singer.',
          'Yes, I do.',
          'I have it on Thursday.',
          'It is in the morning.',
        ],
        correctIndex: 0,
        explanation: 'Câu hỏi bắt đầu bằng "Why" (tại sao) thì câu trả lời bắt đầu bằng "Because" (bởi vì).',
      },
      {
        id: 'f1_q11',
        skill: 'grammar',
        question: 'Điền to-be quá khứ: "Where ______ you last weekend? - I ______ at the campsite."',
        options: ['was / were', 'were / was', 'are / am', 'is / was'],
        correctIndex: 1,
        explanation: 'Chủ ngữ "you" đi với "were", chủ ngữ "I" đi với "was" trong thì quá khứ đơn.',
      },
      {
        id: 'f1_q12',
        skill: 'grammar',
        question: 'Điền từ thích hợp: "______ your sports day in May? - No, it isn\'t. It\'s in June."',
        options: ['Is', 'Are', 'Do', 'Does'],
        correctIndex: 0,
        explanation: '"sports day" là danh từ số ít nên dùng to-be đảo "Is your sports day in May?".',
      },
      {
        id: 'f1_q13',
        skill: 'grammar',
        question: 'Tìm lỗi sai trong câu sau: "He like art because he wants to be a painter."',
        options: ['like (sửa thành likes)', 'because', 'wants', 'a painter'],
        correctIndex: 0,
        explanation: 'Chủ ngữ "He" là ngôi thứ ba số ít, động từ "like" phải thêm s ➔ "likes".',
      },
      {
        id: 'f1_q14',
        skill: 'grammar',
        question: 'Chọn câu viết đúng trật tự từ:',
        options: [
          'Were you in the countryside last summer?',
          'You were in the countryside last summer were?',
          'Were you last summer in countryside the?',
          'Was you in the countryside last summer?',
        ],
        correctIndex: 0,
        explanation: 'Cấu trúc câu hỏi quá khứ chuẩn: "Were you in the countryside last summer?".',
      },
      {
        id: 'f1_q15',
        skill: 'reading',
        passage: "Hoa Lan Primary School is in the village. It is a big school with twenty classrooms. There are two computer rooms and one large music room. The school playground is very big. Every Friday afternoon, the pupils play sports and games there. Today is Friday, Minh and his classmates have English, maths and PE. Minh loves PE because he wants to be a football player.",
        question: 'Where is Hoa Lan Primary School?',
        options: ['In the city', 'In the village', 'In the mountains', 'Near the beach'],
        correctIndex: 1,
        explanation: 'Trong bài viết: "Hoa Lan Primary School is in the village."',
      },
      {
        id: 'f1_q16',
        skill: 'reading',
        passage: "Hoa Lan Primary School is in the village. It is a big school with twenty classrooms. There are two computer rooms and one large music room. The school playground is very big. Every Friday afternoon, the pupils play sports and games there. Today is Friday, Minh and his classmates have English, maths and PE. Minh loves PE because he wants to be a football player.",
        question: 'How many classrooms are there in the school?',
        options: ['12', '15', '20', '25'],
        correctIndex: 2,
        explanation: 'Trong bài: "twenty classrooms" (20 phòng học).',
      },
      {
        id: 'f1_q17',
        skill: 'reading',
        passage: "Hoa Lan Primary School is in the village. It is a big school with twenty classrooms. There are two computer rooms and one large music room. The school playground is very big. Every Friday afternoon, the pupils play sports and games there. Today is Friday, Minh and his classmates have English, maths and PE. Minh loves PE because he wants to be a football player.",
        question: 'How many computer rooms are there?',
        options: ['One', 'Two', 'Three', 'Four'],
        correctIndex: 1,
        explanation: 'Trong bài: "There are two computer rooms".',
      },
      {
        id: 'f1_q18',
        skill: 'reading',
        passage: "Hoa Lan Primary School is in the village. It is a big school with twenty classrooms. There are two computer rooms and one large music room. The school playground is very big. Every Friday afternoon, the pupils play sports and games there. Today is Friday, Minh and his classmates have English, maths and PE. Minh loves PE because he wants to be a football player.",
        question: 'What subjects do Minh and his classmates have today?',
        options: [
          'English, maths and PE',
          'Art, music and science',
          'History, English and IT',
          'Maths, art and music',
        ],
        correctIndex: 0,
        explanation: 'Trong bài: "have English, maths and PE".',
      },
      {
        id: 'f1_q19',
        skill: 'reading',
        passage: "Hoa Lan Primary School is in the village. It is a big school with twenty classrooms. There are two computer rooms and one large music room. The school playground is very big. Every Friday afternoon, the pupils play sports and games there. Today is Friday, Minh and his classmates have English, maths and PE. Minh loves PE because he wants to be a football player.",
        question: 'Why does Minh love PE?',
        options: [
          'Because he wants to be a doctor.',
          'Because he wants to be an English teacher.',
          'Because he wants to be a football player.',
          'Because he wants to be a singer.',
        ],
        correctIndex: 2,
        explanation: 'Trong bài: "because he wants to be a football player" (cầu thủ bóng đá).',
      },
      {
        id: 'f1_q20',
        skill: 'reading',
        passage: "Hoa Lan Primary School is in the village. It is a big school with twenty classrooms. There are two computer rooms and one large music room. The school playground is very big. Every Friday afternoon, the pupils play sports and games there. Today is Friday, Minh and his classmates have English, maths and PE. Minh loves PE because he wants to be a football player.",
        question: 'When do the pupils play sports and games in the playground?',
        options: ['Every Monday morning', 'Every Friday afternoon', 'On Sunday evening', 'On Saturday'],
        correctIndex: 1,
        explanation: 'Trong bài: "Every Friday afternoon, the pupils play sports and games there."',
      },
    ],
  },
  {
    id: 'exam_speed_10',
    title: 'Thử Thách Phản Xạ 10 Phút',
    subtitle: 'Đố nhanh 10 câu ngữ pháp & từ vựng để rèn tốc độ làm bài',
    semester: 1,
    level: 'Thử Thách 10 Phút',
    durationMinutes: 10,
    totalQuestions: 10,
    questions: [
      {
        id: 'sp_q1',
        skill: 'vocab',
        question: 'Từ nào có nghĩa là "vùng nông thôn, miền quê"?',
        options: ['City', 'Countryside', 'Campsite', 'Island'],
        correctIndex: 1,
        explanation: '"Countryside" là vùng quê, nông thôn.',
      },
      {
        id: 'sp_q2',
        skill: 'grammar',
        question: 'Điền từ: "I like art ______ I want to be a painter."',
        options: ['so', 'because', 'but', 'or'],
        correctIndex: 1,
        explanation: '"Because" nghĩa là bởi vì, chỉ lý do.',
      },
      {
        id: 'sp_q3',
        skill: 'grammar',
        question: '"Were you at the zoo yesterday?" - "Yes, I ______."',
        options: ['am', 'were', 'was', 'did'],
        correctIndex: 2,
        explanation: 'Chủ ngữ "I" đi với to-be "was" trong quá khứ.',
      },
      {
        id: 'sp_q4',
        skill: 'vocab',
        question: 'Chọn từ viết đúng chính tả tiếng Anh của từ "thứ Tư":',
        options: ['Wensday', 'Wedensday', 'Wednesday', 'Wedneday'],
        correctIndex: 2,
        explanation: 'Thứ Tư viết chuẩn là "Wednesday".',
      },
      {
        id: 'sp_q5',
        skill: 'grammar',
        question: '"Can your sister swim?" - "______."',
        options: ['Yes, she is.', 'No, she cannot.', 'Yes, I can.', 'No, he cannot.'],
        correctIndex: 1,
        explanation: 'Hỏi "Can your sister (she)...?" trả lời: "No, she cannot" hoặc "Yes, she can".',
      },
      {
        id: 'sp_q6',
        skill: 'vocab',
        question: 'Từ nào chỉ đồ uống?',
        options: ['Chips', 'Lemonade', 'Chicken', 'Bread'],
        correctIndex: 1,
        explanation: '"Lemonade" là nước chanh (đồ uống), các từ còn lại là đồ ăn.',
      },
      {
        id: 'sp_q7',
        skill: 'grammar',
        question: 'Chọn câu hỏi thích hợp cho câu trả lời: "She is from Australia."',
        options: ['Where are you from?', 'Where is she from?', "Where's he from?", 'Where is your school?'],
        correctIndex: 1,
        explanation: 'Hỏi về cô ấy (she) dùng "Where is she from?".',
      },
      {
        id: 'sp_q8',
        skill: 'vocab',
        question: 'Âm đuôi của từ "like" trong phần Phonics đọc là gì?',
        options: ['/t/', '/d/', '/k/', '/s/'],
        correctIndex: 2,
        explanation: 'Từ "like" phát âm là /laɪk/, âm đuôi là /k/.',
      },
      {
        id: 'sp_q9',
        skill: 'grammar',
        question: 'Điền từ: "How many ______ are there in your classroom? - There are thirty."',
        options: ['desk', 'desks', 'a desk', 'the desk'],
        correctIndex: 1,
        explanation: 'Sau "How many" luôn luôn là danh từ đếm được số nhiều có "s" (desks).',
      },
      {
        id: 'sp_q10',
        skill: 'grammar',
        question: '"What time is it?" - "It is ______."',
        options: ['seven o\'clock', 'on Monday', 'in November', 'at school'],
        correctIndex: 0,
        explanation: '"It is seven o\'clock" (Bây giờ là 7 giờ đúng).',
      },
    ],
  },
];
