import { UnitData } from '../types';

export const UNITS_DATA: UnitData[] = [
  {
    id: 0,
    title: 'Starter: Hello Again!',
    subtitleVi: 'Chào hỏi & Hoạt động lớp học, ngoài trời',
    themeColor: 'from-purple-500 to-indigo-600',
    icon: '👋',
    grammar: [
      {
        id: 'st_g1',
        title: 'Chào hỏi & Giới thiệu bạn bè',
        pattern: 'Hello, how are you? - I am fine, thank you. / This is [Name]. Nice to see you.',
        explanation: 'Dùng để chào hỏi sức khỏe lịch sự và giới thiệu bạn bè với nhau trong lớp học.',
        examples: [
          { q: 'Hello. How are you?', a: "I'm fine, thank you.", meaning: 'Xin chào. Bạn khỏe không? - Mình khỏe, cảm ơn bạn.' },
          { q: 'Hi, hi. This is Mary.', a: 'Nice to see you, Mary.', meaning: 'Chào bạn. Đây là Mary. - Rất vui được gặp bạn, Mary.' },
        ],
        zeraTip: '💡 Khi gặp lại bạn bè sau kỳ nghỉ, bé hãy nở nụ cười thật tươi và nói "Nice to see you!" nhé!',
      },
      {
        id: 'st_g2',
        title: 'Mệnh lệnh trong lớp học (Classroom commands)',
        pattern: '[Động từ] ..., please! (Xin mời...)',
        explanation: 'Thầy cô và các bạn dùng để yêu cầu lịch sự trong lớp học, có từ "please" ở cuối câu.',
        examples: [
          { q: 'Come in, please!', a: 'Thank you, teacher.', meaning: 'Xin mời vào lớp!' },
          { q: 'Open your books, please!', a: 'Yes, teacher.', meaning: 'Xin mời cả lớp mở sách ra!' },
          { q: 'Stand up, please! / Sit down, please!', a: 'All stand / sit', meaning: 'Xin mời đứng lên! / Xin mời ngồi xuống!' },
        ],
        zeraTip: '💡 Nhớ luôn có từ "please" để câu nói thêm phần lễ phép và đáng yêu nha!',
      },
    ],
    coreVocab: [
      { id: 'st_v1', word: 'friend', phonetic: '/frend/', meaningVi: 'bạn bè', partOfSpeech: 'n', exampleEn: 'Mary is my good friend.', exampleVi: 'Mary là người bạn tốt của mình.', category: 'Con người' },
      { id: 'st_v2', word: 'come in', phonetic: '/kʌm ɪn/', meaningVi: 'đi vào', partOfSpeech: 'v', exampleEn: 'Come in, please!', exampleVi: 'Xin mời vào!', category: 'Lớp học' },
      { id: 'st_v3', word: 'read aloud', phonetic: '/riːd əˈlaʊd/', meaningVi: 'đọc to', partOfSpeech: 'v', exampleEn: 'Read aloud, please!', exampleVi: 'Xin mời đọc to!', category: 'Lớp học' },
      { id: 'st_v4', word: 'swim', phonetic: '/swɪm/', meaningVi: 'bơi lội', partOfSpeech: 'v', exampleEn: "Minh's hobby is swimming.", exampleVi: 'Sở thích của Minh là bơi lội.', category: 'Hoạt động' },
      { id: 'st_v5', word: 'cycle', phonetic: '/ˈsaɪ.kəl/', meaningVi: 'đạp xe', partOfSpeech: 'v', exampleEn: 'Cycle fast!', exampleVi: 'Đạp xe thật nhanh!', category: 'Hoạt động' },
      { id: 'st_v6', word: 'jump high', phonetic: '/dʒʌmp haɪ/', meaningVi: 'nhảy cao', partOfSpeech: 'v', exampleEn: 'Jump high!', exampleVi: 'Hãy nhảy thật cao!', category: 'Hoạt động' },
      { id: 'st_v7', word: 'kick hard', phonetic: '/kɪk hɑːd/', meaningVi: 'sút bóng mạnh', partOfSpeech: 'v', exampleEn: 'Kick hard into the goal!', exampleVi: 'Sút bóng thật mạnh vào gôn!', category: 'Hoạt động' },
    ],
    extendedVocab: [
      { id: 'st_ev1', word: 'classmate', phonetic: '/ˈklɑːs.meɪt/', meaningVi: 'bạn cùng lớp', partOfSpeech: 'n', exampleEn: 'Nam is my classmate.', exampleVi: 'Nam là bạn cùng lớp của tớ.', isExtended: true, category: 'Mở rộng: Trường lớp' },
      { id: 'st_ev2', word: 'raise your hand', phonetic: '/reɪz jɔː hænd/', meaningVi: 'giơ tay phát biểu', partOfSpeech: 'phrase', exampleEn: 'Raise your hand before speaking.', exampleVi: 'Hãy giơ tay trước khi nói.', isExtended: true, category: 'Mở rộng: Lớp học' },
      { id: 'st_ev3', word: 'listen carefully', phonetic: '/ˈlɪs.ən ˈkeə.fəl.i/', meaningVi: 'lắng nghe chăm chú', partOfSpeech: 'phrase', exampleEn: 'Listen carefully to the teacher.', exampleVi: 'Hãy lắng nghe cô giáo chăm chú.', isExtended: true, category: 'Mở rộng: Lớp học' },
      { id: 'st_ev4', word: 'roller skate', phonetic: '/ˈrəʊ.lə skeɪt/', meaningVi: 'trượt pa-tanh', partOfSpeech: 'v', exampleEn: 'I like to roller skate in the park.', exampleVi: 'Tớ thích trượt pa-tanh ở công viên.', isExtended: true, category: 'Mở rộng: Thể thao' },
    ],
    communication: [
      {
        id: 'st_c1',
        type: 'answer_to_question',
        instruction: 'Cho câu trả lời, hãy chọn câu hỏi đúng nhất của bạn Minh:',
        givenLabel: 'Câu trả lời của bạn Mary:',
        prompt: "I'm fine, thank you. And you?",
        targetLabel: 'Câu hỏi của bạn Minh là:',
        options: [
          'What is your name?',
          'Hello, Mary. How are you?',
          'Where are you from?',
          'What time is it?',
        ],
        correctIndex: 1,
        explanation: 'Khi Mary trả lời "I\'m fine, thank you", câu hỏi phù hợp nhất là hỏi thăm sức khỏe: "How are you?".',
      },
      {
        id: 'st_c2',
        type: 'question_to_answer',
        instruction: 'Cho câu hỏi, hãy chọn câu trả lời đúng:',
        givenLabel: 'Lời giới thiệu của cô giáo:',
        prompt: 'This is our new friend, Linh.',
        targetLabel: 'Các bạn học sinh trong lớp sẽ chào đáp lại là:',
        options: [
          'I am going to school.',
          'Nice to see you, Linh!',
          'It is Monday today.',
          'I want some chips.',
        ],
        correctIndex: 1,
        explanation: 'Khi được giới thiệu một người bạn mới, chúng ta lịch sự đáp "Nice to see you, Linh!" (Rất vui được gặp bạn).',
      },
    ],
    phonics: [
      {
        id: 'st_ph1',
        letterSound: 'f',
        word: 'friend',
        phonetic: '/frend/',
        sentence: 'This is my good friend.',
        translation: 'Đây là người bạn tốt của mình.',
        tip: 'Âm /f/ là âm vô thanh: đặt răng cửa hàm trên chạm nhẹ môi dưới và thổi luồng hơi ra.',
      },
      {
        id: 'st_ph2',
        letterSound: 'sw',
        word: 'swim',
        phonetic: '/swɪm/',
        sentence: 'I like to swim in summer.',
        translation: 'Mình thích bơi lội vào mùa hè.',
        tip: 'Tổ hợp âm /sw/: lướt nhanh từ âm /s/ sang âm /w/ tròn môi.',
      },
      {
        id: 'st_ph3',
        letterSound: 'cl',
        word: 'classmate',
        phonetic: '/ˈklɑːs.meɪt/',
        sentence: 'Nam is my friendly classmate.',
        translation: 'Nam là người bạn cùng lớp thân thiện của mình.',
        tip: 'Tổ hợp âm /kl/: bật nhẹ âm /k/ rồi chuyển nhanh sang âm /l/.',
      },
      {
        id: 'st_ph4',
        letterSound: 'r',
        word: 'read',
        phonetic: '/riːd/',
        sentence: 'Read aloud please, children!',
        translation: 'Các em hãy đọc to lên nào!',
        tip: 'Âm /r/ phát âm tròn môi, uốn nhẹ đầu lưỡi về phía sau và không để lưỡi chạm vòm miệng.',
      },
    ],
    reading: {
      id: 'st_r1',
      title: 'A Fun Day At School (Ngày vui ở trường)',
      unitId: 0,
      imageTheme: 'school_friends',
      passageEn: 'Hello! My name is Minh. I am ten years old. Today I am happy to meet my friends again at school. This is Mary. This is Nam. We are in the school yard. Nam likes football and he can kick hard. Mary likes jumping high. Our teacher is Ms Hoa. She is very kind.',
      passageVi: 'Xin chào! Tên mình là Minh. Mình mười tuổi. Hôm nay mình rất vui khi được gặp lại các bạn ở trường. Đây là Mary. Đây là Nam. Chúng mình đang ở sân trường. Nam thích bóng đá và bạn ấy có thể sút rất mạnh. Mary thích nhảy cao. Cô giáo của chúng mình là cô Hoa. Cô rất tốt bụng.',
      questions: [
        {
          id: 'st_rq1',
          question: 'How does Minh feel today? (Minh cảm thấy thế nào hôm nay?)',
          options: ['He is sad.', 'He is happy.', 'He is tired.', 'He is sleepy.'],
          correctIndex: 1,
          explanation: 'Trong bài đọc: "Today I am happy to meet my friends again".',
        },
        {
          id: 'st_rq2',
          question: 'What does Nam like? (Nam thích môn gì?)',
          options: ['Football', 'Swimming', 'Music', 'Drawing'],
          correctIndex: 0,
          explanation: 'Trong bài: "Nam likes football and he can kick hard."',
        },
        {
          id: 'st_rq3',
          question: 'Who is their teacher? (Ai là giáo viên của các bạn?)',
          options: ['Mr Long', 'Ms Hoa', 'Ms Linh', 'Mr Brown'],
          correctIndex: 1,
          explanation: 'Trong bài: "Our teacher is Ms Hoa."',
        },
      ],
    },
  },
  {
    id: 1,
    title: 'Unit 1: My Friends',
    subtitleVi: 'Bạn bè & Các quốc gia trên thế giới',
    themeColor: 'from-purple-600 to-violet-700',
    icon: '🌏',
    grammar: [
      {
        id: 'u1_g1',
        title: 'Hỏi và trả lời về quê hương của bạn (Where are you from?)',
        pattern: 'Where are you from? - I am from + [Tên quốc gia].',
        explanation: 'Dùng khi muốn hỏi một người bạn đến từ đất nước nào.',
        examples: [
          { q: 'Where are you from, Minh?', a: "I'm from Viet Nam.", meaning: 'Bạn đến từ đâu vậy Minh? - Mình đến từ Việt Nam.' },
          { q: 'Where are you from, Mary?', a: "I'm from America.", meaning: 'Bạn đến từ đâu vậy Mary? - Mình đến từ nước Mỹ.' },
        ],
        zeraTip: '💡 Nhớ dùng "I am from" hoặc viết tắt "I\'m from" trước tên quốc gia nhé!',
      },
      {
        id: 'u1_g2',
        title: 'Hỏi và trả lời về quê hương của người khác (He / She)',
        pattern: "Where is he/she from? - He's / She's from + [Tên quốc gia].",
        explanation: 'Dùng để hỏi một bạn nam (he) hoặc bạn nữ (she) đến từ quốc gia nào.',
        examples: [
          { q: "Where's he from?", a: "He's from Australia.", meaning: 'Bạn ấy (nam) đến từ đâu? - Bạn ấy đến từ nước Úc.' },
          { q: "Where's she from?", a: "She's from Japan.", meaning: 'Bạn ấy (nữ) đến từ đâu? - Bạn ấy đến từ Nhật Bản.' },
        ],
        zeraTip: '💡 "Where\'s" là viết tắt của "Where is". He dành cho bạn nam, She dành cho bạn nữ!',
      },
    ],
    coreVocab: [
      { id: 'u1_v1', word: 'Viet Nam', phonetic: '/ˌvjetˈnæm/', meaningVi: 'nước Việt Nam', partOfSpeech: 'n', exampleEn: "I'm from Viet Nam.", exampleVi: 'Mình đến từ Việt Nam.', category: 'Quốc gia' },
      { id: 'u1_v2', word: 'America', phonetic: '/əˈmer.ɪ.kə/', meaningVi: 'nước Mỹ (Hoa Kỳ)', partOfSpeech: 'n', exampleEn: "Mary is from America.", exampleVi: 'Mary đến từ nước Mỹ.', category: 'Quốc gia' },
      { id: 'u1_v3', word: 'Australia', phonetic: '/ɒsˈtreɪ.li.ə/', meaningVi: 'nước Úc (Ô-xtrây-li-a)', partOfSpeech: 'n', exampleEn: "Ben is from Australia.", exampleVi: 'Ben đến từ nước Úc.', category: 'Quốc gia' },
      { id: 'u1_v4', word: 'Britain', phonetic: '/ˈbrɪt.ən/', meaningVi: 'nước Anh (Vương quốc Anh)', partOfSpeech: 'n', exampleEn: "Lucy is from Britain.", exampleVi: 'Lucy đến từ nước Anh.', category: 'Quốc gia' },
      { id: 'u1_v5', word: 'Japan', phonetic: '/dʒəˈpæn/', meaningVi: 'nước Nhật Bản', partOfSpeech: 'n', exampleEn: "She is from Japan.", exampleVi: 'Cô ấy đến từ Nhật Bản.', category: 'Quốc gia' },
      { id: 'u1_v6', word: 'Malaysia', phonetic: '/məˈleɪ.ʒə/', meaningVi: 'nước Ma-lai-xi-a', partOfSpeech: 'n', exampleEn: "He is from Malaysia.", exampleVi: 'Cậu ấy đến từ Malaysia.', category: 'Quốc gia' },
      { id: 'u1_v7', word: 'Singapore', phonetic: '/ˌsɪŋ.əˈpɔːr/', meaningVi: 'nước Xin-ga-po', partOfSpeech: 'n', exampleEn: "My friend is from Singapore.", exampleVi: 'Bạn tớ đến từ Singapore.', category: 'Quốc gia' },
      { id: 'u1_v8', word: 'Thailand', phonetic: '/ˈtaɪ.lænd/', meaningVi: 'nước Thái Lan', partOfSpeech: 'n', exampleEn: "She is from Thailand.", exampleVi: 'Cô ấy đến từ Thái Lan.', category: 'Quốc gia' },
    ],
    extendedVocab: [
      { id: 'u1_ev1', word: 'Canada', phonetic: '/ˈkæn.ə.də/', meaningVi: 'nước Ca-na-đa', partOfSpeech: 'n', exampleEn: "He's from Canada.", exampleVi: 'Cậu ấy đến từ Canada.', isExtended: true, category: 'Mở rộng: Quốc gia' },
      { id: 'u1_ev2', word: 'South Korea', phonetic: '/ˌsaʊθ kəˈriː.ə/', meaningVi: 'Hàn Quốc', partOfSpeech: 'n', exampleEn: "My cousin is from South Korea.", exampleVi: 'Anh họ tớ đến từ Hàn Quốc.', isExtended: true, category: 'Mở rộng: Quốc gia' },
      { id: 'u1_ev3', word: 'France', phonetic: '/frɑːns/', meaningVi: 'nước Pháp', partOfSpeech: 'n', exampleEn: "She is from France.", exampleVi: 'Cô ấy đến từ nước Pháp.', isExtended: true, category: 'Mở rộng: Quốc gia' },
      { id: 'u1_ev4', word: 'Hanoi', phonetic: '/hæˈnɔɪ/', meaningVi: 'Hà Nội (Thủ đô Việt Nam)', partOfSpeech: 'n', exampleEn: 'Hanoi is the capital of Viet Nam.', exampleVi: 'Hà Nội là thủ đô của Việt Nam.', isExtended: true, category: 'Mở rộng: Thủ đô' },
      { id: 'u1_ev5', word: 'London', phonetic: '/ˈlʌn.dən/', meaningVi: 'Luân Đôn (Thủ đô nước Anh)', partOfSpeech: 'n', exampleEn: 'Lucy lives in London.', exampleVi: 'Lucy sống ở Luân Đôn.', isExtended: true, category: 'Mở rộng: Thủ đô' },
      { id: 'u1_ev6', word: 'Washington DC', phonetic: '/ˈwɒʃ.ɪŋ.tən diː siː/', meaningVi: 'Thủ đô nước Mỹ', partOfSpeech: 'n', exampleEn: 'Washington DC is in America.', exampleVi: 'Washington DC ở nước Mỹ.', isExtended: true, category: 'Mở rộng: Thủ đô' },
    ],
    communication: [
      {
        id: 'u1_c1',
        type: 'answer_to_question',
        instruction: 'Cho câu trả lời, hãy chọn câu hỏi chính xác:',
        givenLabel: 'Câu trả lời của bạn Mary:',
        prompt: "I'm from America.",
        targetLabel: 'Câu hỏi của bạn Minh là:',
        options: [
          'Where are you from?',
          'What is that?',
          'Can you swim?',
          'When is your birthday?',
        ],
        correctIndex: 0,
        explanation: 'Mary trả lời nơi mình đến "I\'m from America", nên câu hỏi là "Where are you from?".',
      },
      {
        id: 'u1_c2',
        type: 'answer_to_question',
        instruction: 'Cho câu trả lời, hãy chọn câu hỏi phù hợp:',
        givenLabel: 'Câu trả lời của bạn Ben:',
        prompt: "She's from Japan.",
        targetLabel: 'Câu hỏi của bạn Lucy là:',
        options: [
          "Where's he from?",
          "Where's she from?",
          'Who is that boy?',
          'What does she do?',
        ],
        correctIndex: 1,
        explanation: 'Câu trả lời có đại từ "She\'s", vậy câu hỏi phải hỏi về bạn nữ: "Where\'s she from?".',
      },
      {
        id: 'u1_c3',
        type: 'question_to_answer',
        instruction: 'Cho câu hỏi, hãy chọn câu trả lời đúng:',
        givenLabel: 'Câu hỏi của bạn học sinh:',
        prompt: 'Where is your new friend from?',
        targetLabel: 'Câu trả lời chính xác là:',
        options: [
          'He is nine years old.',
          "He's from Singapore.",
          'He can play the guitar.',
          'It is in the village.',
        ],
        correctIndex: 1,
        explanation: 'Hỏi về quê hương nơi xuất xứ ("Where... from"), trả lời là "He\'s from Singapore".',
      },
    ],
    phonics: [
      {
        id: 'u1_ph1',
        letterSound: 'a',
        word: 'America',
        phonetic: '/əˈmer.ɪ.kə/',
        sentence: "I'm from America.",
        translation: 'Mình đến từ nước Mỹ.',
        tip: 'Âm /ə/ là âm schwa nhẹ nhàng, thả lỏng môi miệng khi phát âm đầu từ America.',
      },
      {
        id: 'u1_ph2',
        letterSound: 'ia',
        word: 'Australia',
        phonetic: '/ɒsˈtreɪ.li.ə/',
        sentence: "She's from Australia.",
        translation: 'Bạn ấy đến từ nước Úc.',
        tip: 'Đuôi -ia trong Australia phát âm là /li.ə/, lướt nhẹ và tự nhiên.',
      },
      {
        id: 'u1_ph3',
        letterSound: 'v',
        word: 'Viet Nam',
        phonetic: '/ˌvjetˈnæm/',
        sentence: "I'm from Viet Nam.",
        translation: 'Mình đến từ Việt Nam.',
        tip: 'Âm /v/ là âm hữu thanh: răng trên chạm nhẹ môi dưới và làm rung thanh quản.',
      },
      {
        id: 'u1_ph4',
        letterSound: 'j',
        word: 'Japan',
        phonetic: '/dʒəˈpæn/',
        sentence: 'Aki is from Japan.',
        translation: 'Aki đến từ đất nước Nhật Bản.',
        tip: 'Âm /dʒ/: tròn môi, bật nhẹ âm hữu thanh từ vòm họng.',
      },
      {
        id: 'u1_ph5',
        letterSound: 'm',
        word: 'Malaysia',
        phonetic: '/məˈleɪ.ʒə/',
        sentence: 'Ben is from Malaysia.',
        translation: 'Ben đến từ nước Ma-lai-xi-a.',
        tip: 'Âm /m/: khép hai môi lại và ngân âm qua khoang mũi.',
      },
    ],
    reading: {
      id: 'u1_r1',
      title: 'Minh and His International Friends (Trang 15 - SGK)',
      unitId: 1,
      imageTheme: 'friends_flags',
      passageEn: 'Hello. I am Minh. I am nine years old. I am from Viet Nam. I have two new friends, Tony and Laura. Tony is from America. Laura is from Australia. They are friendly.',
      passageVi: 'Xin chào. Mình là Minh. Mình chín tuổi. Mình đến từ Việt Nam. Mình có hai người bạn mới là Tony và Laura. Tony đến từ nước Mỹ. Laura đến từ nước Úc. Các bạn ấy rất thân thiện.',
      questions: [
        {
          id: 'u1_rq1',
          question: 'How old is Minh? (Minh bao nhiêu tuổi?)',
          options: ['Eight years old', 'Nine years old', 'Ten years old', 'Seven years old'],
          correctIndex: 1,
          explanation: 'Trong bài viết: "I am nine years old."',
        },
        {
          id: 'u1_rq2',
          question: 'Where is Minh from? (Minh đến từ đâu?)',
          options: ['Britain', 'America', 'Viet Nam', 'Australia'],
          correctIndex: 2,
          explanation: 'Trong bài viết: "I am from Viet Nam."',
        },
        {
          id: 'u1_rq3',
          question: 'Where is Tony from? (Tony đến từ đâu?)',
          options: ['America', 'Australia', 'Japan', 'Malaysia'],
          correctIndex: 0,
          explanation: 'Trong bài viết: "Tony is from America."',
        },
        {
          id: 'u1_rq4',
          question: 'Where is Laura from? (Laura đến từ đâu?)',
          options: ['Thailand', 'Singapore', 'Australia', 'Viet Nam'],
          correctIndex: 2,
          explanation: 'Trong bài viết: "Laura is from Australia."',
        },
      ],
    },
  },
  {
    id: 2,
    title: 'Unit 2: Time and Daily Routines',
    subtitleVi: 'Xem giờ & Thói quen sinh hoạt hàng ngày',
    themeColor: 'from-violet-600 to-purple-800',
    icon: '⏰',
    grammar: [
      {
        id: 'u2_g1',
        title: 'Hỏi và nói giờ (What time is it?)',
        pattern: "What time is it? - It's + [Giờ] + [Phút] / [Giờ] o'clock.",
        explanation: 'Dùng khi muốn biết giờ giấc hiện tại.',
        examples: [
          { q: 'What time is it?', a: "It's six o'clock.", meaning: 'Mấy giờ rồi? - Bây giờ là 6 giờ đúng.' },
          { q: 'What time is it?', a: "It's six fifteen / six thirty.", meaning: 'Mấy giờ rồi? - 6 giờ 15 / 6 giờ 30.' },
        ],
        zeraTip: '💡 "o\'clock" chỉ dùng cho giờ chẵn (ví dụ 6:00, 8:00). Có số phút thì đọc Giờ trước, Phút sau nhé!',
      },
      {
        id: 'u2_g2',
        title: 'Hỏi thời gian làm việc hàng ngày (What time do you...?)',
        pattern: 'What time do you + [hành động]? - I + [hành động] at + [thời gian].',
        explanation: 'Dùng để hỏi xem ai đó thường làm việc gì vào lúc mấy giờ.',
        examples: [
          { q: 'What time do you get up?', a: 'I get up at six o’clock.', meaning: 'Bạn thức dậy lúc mấy giờ? - Mình thức dậy lúc 6 giờ.' },
          { q: 'What time do you go to bed?', a: 'I go to bed at nine forty-five.', meaning: 'Bạn đi ngủ lúc mấy giờ? - Mình đi ngủ lúc 9 giờ 45.' },
        ],
        zeraTip: '💡 Luôn dùng giới từ "at" trước mốc thời gian (ví dụ: at 7:00, at six thirty)!',
      },
    ],
    coreVocab: [
      { id: 'u2_v1', word: "o'clock", phonetic: "/əˈklɒk/", meaningVi: 'giờ đúng (giờ chẵn)', partOfSpeech: 'adv', exampleEn: "It is eight o'clock.", exampleVi: 'Bây giờ là 8 giờ đúng.', category: 'Thời gian' },
      { id: 'u2_v2', word: 'fifteen', phonetic: '/ˌfɪfˈtiːn/', meaningVi: 'số 15 (15 phút)', partOfSpeech: 'num', exampleEn: "It's six fifteen.", exampleVi: 'Bây giờ là 6 giờ 15 phút.', category: 'Thời gian' },
      { id: 'u2_v3', word: 'thirty', phonetic: '/ˈθɜː.ti/', meaningVi: 'số 30 (30 phút / rưỡi)', partOfSpeech: 'num', exampleEn: "It's eight thirty.", exampleVi: 'Bây giờ là 8 giờ 30.', category: 'Thời gian' },
      { id: 'u2_v4', word: 'forty-five', phonetic: '/ˌfɔː.tiˈfaɪv/', meaningVi: 'số 45 (45 phút)', partOfSpeech: 'num', exampleEn: "It's six forty-five.", exampleVi: 'Bây giờ là 6 giờ 45.', category: 'Thời gian' },
      { id: 'u2_v5', word: 'get up', phonetic: '/ɡet ʌp/', meaningVi: 'thức dậy', partOfSpeech: 'phrase', exampleEn: 'I get up at six o’clock.', exampleVi: 'Tớ thức dậy lúc 6 giờ.', category: 'Hoạt động hàng ngày' },
      { id: 'u2_v6', word: 'have breakfast', phonetic: '/hæv ˈbrek.fəst/', meaningVi: 'ăn sáng', partOfSpeech: 'phrase', exampleEn: 'I have breakfast at six fifteen.', exampleVi: 'Tớ ăn sáng lúc 6 giờ 15.', category: 'Hoạt động hàng ngày' },
      { id: 'u2_v7', word: 'go to school', phonetic: '/ɡəʊ tə skuːl/', meaningVi: 'đi học', partOfSpeech: 'phrase', exampleEn: 'I go to school at seven o’clock.', exampleVi: 'Tớ đi học lúc 7 giờ.', category: 'Hoạt động hàng ngày' },
      { id: 'u2_v8', word: 'go to bed', phonetic: '/ɡəʊ tə bed/', meaningVi: 'đi ngủ', partOfSpeech: 'phrase', exampleEn: 'I go to bed at nine forty-five.', exampleVi: 'Tớ đi ngủ lúc 9 giờ 45.', category: 'Hoạt động hàng ngày' },
    ],
    extendedVocab: [
      { id: 'u2_ev1', word: 'have lunch', phonetic: '/hæv lʌntʃ/', meaningVi: 'ăn trưa', partOfSpeech: 'phrase', exampleEn: 'I have lunch at school.', exampleVi: 'Tớ ăn trưa ở trường.', isExtended: true, category: 'Mở rộng: Bữa ăn' },
      { id: 'u2_ev2', word: 'have dinner', phonetic: '/hæv ˈdɪn.ər/', meaningVi: 'ăn tối', partOfSpeech: 'phrase', exampleEn: 'I have dinner at home at seven thirty.', exampleVi: 'Tớ ăn tối ở nhà lúc 7 giờ 30.', isExtended: true, category: 'Mở rộng: Bữa ăn' },
      { id: 'u2_ev3', word: 'clean teeth', phonetic: '/kliːn tiːθ/', meaningVi: 'đánh răng', partOfSpeech: 'phrase', exampleEn: 'I clean my teeth every morning.', exampleVi: 'Tớ đánh răng mỗi sáng.', isExtended: true, category: 'Mở rộng: Vệ sinh' },
      { id: 'u2_ev4', word: 'wash face', phonetic: '/wɒʃ feɪs/', meaningVi: 'rửa mặt', partOfSpeech: 'phrase', exampleEn: 'I wash my face after getting up.', exampleVi: 'Tớ rửa mặt sau khi thức dậy.', isExtended: true, category: 'Mở rộng: Vệ sinh' },
      { id: 'u2_ev5', word: 'do homework', phonetic: '/duː ˈhəʊm.wɜːk/', meaningVi: 'làm bài tập về nhà', partOfSpeech: 'phrase', exampleEn: 'I do my homework in the evening.', exampleVi: 'Tớ làm bài tập về nhà vào buổi tối.', isExtended: true, category: 'Mở rộng: Học tập' },
    ],
    communication: [
      {
        id: 'u2_c1',
        type: 'answer_to_question',
        instruction: 'Cho câu trả lời, hãy chọn câu hỏi phù hợp nhất:',
        givenLabel: 'Câu trả lời của bạn Mary:',
        prompt: "It's eight thirty.",
        targetLabel: 'Câu hỏi của bạn Bill là:',
        options: [
          'What time is it?',
          'What time do you get up?',
          'Where are you from?',
          'What day is it today?',
        ],
        correctIndex: 0,
        explanation: 'Mary nói giờ hiện tại ("It\'s eight thirty"), nên câu hỏi là "What time is it?".',
      },
      {
        id: 'u2_c2',
        type: 'answer_to_question',
        instruction: 'Cho câu trả lời, hãy chọn câu hỏi tương ứng:',
        givenLabel: 'Câu trả lời của bạn Nam:',
        prompt: 'I have breakfast at six fifteen.',
        targetLabel: 'Câu hỏi của bạn học sinh là:',
        options: [
          'Where do you have breakfast?',
          'What time do you have breakfast?',
          'Can you have breakfast?',
          'When is your birthday?',
        ],
        correctIndex: 1,
        explanation: 'Nam trả lời thời gian ăn sáng với mốc giờ "at six fifteen", câu hỏi là "What time do you have breakfast?".',
      },
      {
        id: 'u2_c3',
        type: 'question_to_answer',
        instruction: 'Cho câu hỏi, hãy chọn câu trả lời đúng:',
        givenLabel: 'Câu hỏi của cô giáo:',
        prompt: 'What time do you go to bed?',
        targetLabel: 'Bé sẽ trả lời là:',
        options: [
          'I go to bed at nine thirty.',
          'I am from Viet Nam.',
          'It is Tuesday today.',
          'I want some lemonade.',
        ],
        correctIndex: 0,
        explanation: '"What time do you go to bed?" hỏi giờ đi ngủ, trả lời "I go to bed at nine thirty".',
      },
    ],
    phonics: [
      {
        id: 'u2_ph1',
        letterSound: 't',
        word: 'get',
        phonetic: '/ɡet/',
        sentence: 'What time do you get up?',
        translation: 'Bạn thức dậy lúc mấy giờ?',
        tip: 'Âm /t/ ở cuối từ bật dứt khoát đầu lưỡi chạm vào vòm miệng trên.',
      },
      {
        id: 'u2_ph2',
        letterSound: 'd',
        word: 'bed',
        phonetic: '/bed/',
        sentence: 'What time do you go to bed?',
        translation: 'Bạn đi ngủ lúc mấy giờ?',
        tip: 'Âm /d/ là âm hữu thanh, rung thanh quản khi phát âm cuối từ "bed".',
      },
      {
        id: 'u2_ph3',
        letterSound: 'cl',
        word: 'clock',
        phonetic: '/klɒk/',
        sentence: 'Look at the big clock on the wall.',
        translation: 'Hãy nhìn chiếc đồng hồ lớn trên tường kìa.',
        tip: 'Tổ hợp âm /kl/: phát âm gọn gàng, âm đuôi /k/ bật nhẹ.',
      },
      {
        id: 'u2_ph4',
        letterSound: 'st',
        word: 'breakfast',
        phonetic: '/ˈbrek.fəst/',
        sentence: 'I have breakfast at six thirty.',
        translation: 'Mình ăn sáng lúc sáu giờ ba mươi.',
        tip: 'Đuôi -st đọc là /st/, lướt từ âm /s/ xì hơi sang âm /t/ dứt khoát.',
      },
      {
        id: 'u2_ph5',
        letterSound: 'sh',
        word: 'shower',
        phonetic: '/ˈʃaʊ.ər/',
        sentence: 'I take a shower every morning.',
        translation: 'Mình tắm vòi hoa sen vào mỗi buổi sáng.',
        tip: 'Âm /ʃ/ chu tròn môi, đẩy luồng hơi mạnh qua khe giữa lưỡi và vòm họng.',
      },
    ],
    reading: {
      id: 'u2_r1',
      title: 'A Pupil at Hoa Lan Primary School (Trang 21 - SGK)',
      unitId: 2,
      imageTheme: 'clock_routine',
      passageEn: 'I am a pupil at Hoa Lan Primary School. I get up at six o’clock. I wash my face and clean my teeth. Then I have breakfast at six fifteen. I go to school at seven o’clock. I have lunch at school. I have dinner at home at seven thirty. I do my homework and go to bed at nine forty-five.',
      passageVi: 'Mình là học sinh trường Tiểu học Hoa Lan. Mình thức dậy lúc 6 giờ đúng. Mình rửa mặt và đánh răng. Sau đó mình ăn sáng lúc 6 giờ 15. Mình đi học lúc 7 giờ. Mình ăn trưa ở trường. Mình ăn tối ở nhà lúc 7 giờ 30. Mình làm bài tập về nhà và đi ngủ lúc 9 giờ 45.',
      questions: [
        {
          id: 'u2_rq1',
          question: 'What time does the pupil get up? (Bạn học sinh thức dậy lúc mấy giờ?)',
          options: ['At 6:00', 'At 6:15', 'At 7:00', 'At 7:30'],
          correctIndex: 0,
          explanation: 'Trong bài: "I get up at six o’clock" (6:00).',
        },
        {
          id: 'u2_rq2',
          question: 'What does he do at 6:15? (Bạn ấy làm gì lúc 6:15?)',
          options: ['Go to school', 'Have breakfast', 'Have lunch', 'Go to bed'],
          correctIndex: 1,
          explanation: 'Trong bài: "Then I have breakfast at six fifteen."',
        },
        {
          id: 'u2_rq3',
          question: 'Where does he have lunch? (Bạn ấy ăn trưa ở đâu?)',
          options: ['At home', 'At school', 'At the restaurant', 'At the park'],
          correctIndex: 1,
          explanation: 'Trong bài: "I have lunch at school."',
        },
        {
          id: 'u2_rq4',
          question: 'What time does he go to bed? (Bạn ấy đi ngủ lúc mấy giờ?)',
          options: ['At 9:15', 'At 9:30', 'At 9:45', 'At 10:00'],
          correctIndex: 2,
          explanation: 'Trong bài: "go to bed at nine forty-five" (9:45).',
        },
      ],
    },
  },
  {
    id: 3,
    title: 'Unit 3: My Week',
    subtitleVi: 'Các ngày trong tuần & Hoạt động yêu thích',
    themeColor: 'from-purple-700 to-indigo-800',
    icon: '📅',
    grammar: [
      {
        id: 'u3_g1',
        title: 'Hỏi hôm nay là thứ mấy (What day is it today?)',
        pattern: "What day is it today? - It's + [Thứ trong tuần].",
        explanation: 'Dùng khi muốn biết hôm nay là ngày thứ mấy trong tuần.',
        examples: [
          { q: 'What day is it today?', a: "It's Monday.", meaning: 'Hôm nay là thứ mấy? - Hôm nay là thứ Hai.' },
          { q: 'What day is it today?', a: "It's Friday.", meaning: 'Hôm nay là thứ mấy? - Hôm nay là thứ Sáu.' },
        ],
        zeraTip: '💡 Các thứ trong tuần trong tiếng Anh luôn viết hoa chữ cái đầu tiên nhé (Monday, Tuesday...)!',
      },
      {
        id: 'u3_g2',
        title: 'Hỏi bạn làm gì vào một ngày trong tuần (What do you do on...?)',
        pattern: 'What do you do on + [Thứ + s]? - I + [hành động].',
        explanation: 'Dùng để hỏi về thói quen làm gì vào những ngày thứ cụ thể.',
        examples: [
          { q: 'What do you do on Thursdays?', a: 'I study at school.', meaning: 'Bạn làm gì vào các ngày thứ Năm? - Mình học ở trường.' },
          { q: 'What do you do on Saturdays?', a: 'I do housework.', meaning: 'Bạn làm gì vào các ngày thứ Bảy? - Mình làm việc nhà.' },
        ],
        zeraTip: '💡 Thêm "s" sau tên thứ (on Mondays, on Sundays) mang ý nghĩa lặp lại đều đặn vào các ngày thứ đó!',
      },
    ],
    coreVocab: [
      { id: 'u3_v1', word: 'Monday', phonetic: '/ˈmʌn.deɪ/', meaningVi: 'thứ Hai', partOfSpeech: 'n', exampleEn: "It's Monday today.", exampleVi: 'Hôm nay là thứ Hai.', category: 'Ngày trong tuần' },
      { id: 'u3_v2', word: 'Tuesday', phonetic: '/ˈtjuːz.deɪ/', meaningVi: 'thứ Ba', partOfSpeech: 'n', exampleEn: 'I have English on Tuesday.', exampleVi: 'Tớ có tiết Tiếng Anh vào thứ Ba.', category: 'Ngày trong tuần' },
      { id: 'u3_v3', word: 'Wednesday', phonetic: '/ˈwenz.deɪ/', meaningVi: 'thứ Tư', partOfSpeech: 'n', exampleEn: "It is Wednesday.", exampleVi: 'Hôm nay là thứ Tư.', category: 'Ngày trong tuần' },
      { id: 'u3_v4', word: 'Thursday', phonetic: '/ˈθɜːz.deɪ/', meaningVi: 'thứ Năm', partOfSpeech: 'n', exampleEn: 'I study at school on Thursday.', exampleVi: 'Tớ học ở trường vào thứ Năm.', category: 'Ngày trong tuần' },
      { id: 'u3_v5', word: 'Friday', phonetic: '/ˈfraɪ.deɪ/', meaningVi: 'thứ Sáu', partOfSpeech: 'n', exampleEn: "It's Friday, let's play!", exampleVi: 'Thứ Sáu rồi, cùng chơi nào!', category: 'Ngày trong tuần' },
      { id: 'u3_v6', word: 'Saturday', phonetic: '/ˈsæt.ə.deɪ/', meaningVi: 'thứ Bảy', partOfSpeech: 'n', exampleEn: 'I stay at home on Saturday.', exampleVi: 'Tớ ở nhà vào thứ Bảy.', category: 'Ngày trong tuần' },
      { id: 'u3_v7', word: 'Sunday', phonetic: '/ˈsʌn.deɪ/', meaningVi: 'Chủ Nhật', partOfSpeech: 'n', exampleEn: 'I listen to music on Sunday.', exampleVi: 'Tớ nghe nhạc vào Chủ Nhật.', category: 'Ngày trong tuần' },
      { id: 'u3_v8', word: 'do housework', phonetic: '/duː ˈhaʊs.wɜːk/', meaningVi: 'làm việc nhà', partOfSpeech: 'phrase', exampleEn: 'I do housework on Saturdays.', exampleVi: 'Tớ giúp làm việc nhà vào thứ Bảy.', category: 'Hoạt động' },
      { id: 'u3_v9', word: 'listen to music', phonetic: '/ˈlɪs.ən tə ˈmjuː.zɪk/', meaningVi: 'nghe nhạc', partOfSpeech: 'phrase', exampleEn: 'She listens to music.', exampleVi: 'Cô ấy nghe nhạc.', category: 'Hoạt động' },
    ],
    extendedVocab: [
      { id: 'u3_ev1', word: 'weekend', phonetic: '/ˌwiːkˈend/', meaningVi: 'ngày cuối tuần (thứ 7 & CN)', partOfSpeech: 'n', exampleEn: 'At the weekend, I stay at home.', exampleVi: 'Vào cuối tuần, tớ ở nhà.', isExtended: true, category: 'Mở rộng: Thời gian' },
      { id: 'u3_ev2', word: 'weekday', phonetic: '/ˈwiːk.deɪ/', meaningVi: 'ngày trong tuần (từ thứ 2 đến thứ 6)', partOfSpeech: 'n', exampleEn: 'I go to school on weekdays.', exampleVi: 'Tớ đi học vào các ngày trong tuần.', isExtended: true, category: 'Mở rộng: Thời gian' },
      { id: 'u3_ev3', word: 'play football', phonetic: '/pleɪ ˈfʊt.bɔːl/', meaningVi: 'chơi đá bóng', partOfSpeech: 'phrase', exampleEn: 'On Saturdays, I play football with friends.', exampleVi: 'Vào thứ Bảy, tớ đá bóng với các bạn.', isExtended: true, category: 'Mở rộng: Thể thao' },
      { id: 'u3_ev4', word: 'visit grandparents', phonetic: '/ˈvɪz.ɪt ˈɡræn.peə.rənts/', meaningVi: 'thăm ông bà', partOfSpeech: 'phrase', exampleEn: 'We visit our grandparents on Sundays.', exampleVi: 'Chúng tớ thăm ông bà vào Chủ Nhật.', isExtended: true, category: 'Mở rộng: Gia đình' },
    ],
    communication: [
      {
        id: 'u3_c1',
        type: 'answer_to_question',
        instruction: 'Cho câu trả lời, hãy chọn câu hỏi tương ứng:',
        givenLabel: 'Câu trả lời của bạn học sinh:',
        prompt: "It's Thursday.",
        targetLabel: 'Câu hỏi của cô giáo là:',
        options: [
          'What time is it?',
          'What day is it today?',
          'Where are you from?',
          'Can you play the piano?',
        ],
        correctIndex: 1,
        explanation: 'Trả lời ngày thứ ("It\'s Thursday"), câu hỏi phải là "What day is it today?".',
      },
      {
        id: 'u3_c2',
        type: 'answer_to_question',
        instruction: 'Cho câu trả lời, hãy chọn câu hỏi phù hợp:',
        givenLabel: 'Câu trả lời của bạn Linh:',
        prompt: 'I do housework and listen to music.',
        targetLabel: 'Câu hỏi của bạn Minh là:',
        options: [
          'What do you do on Sundays?',
          'Where is your school?',
          'What time do you go to bed?',
          'When is your birthday?',
        ],
        correctIndex: 0,
        explanation: 'Linh kể về việc mình làm "I do housework and listen to music", câu hỏi là "What do you do on Sundays?".',
      },
    ],
    phonics: [
      {
        id: 'u3_ph1',
        letterSound: 'u',
        word: 'music',
        phonetic: '/ˈmjuː.zɪk/',
        sentence: 'I listen to music on Saturdays.',
        translation: 'Mình nghe nhạc vào các ngày thứ Bảy.',
        tip: 'Chữ cái "u" trong "music" phát âm là /juː/.',
      },
      {
        id: 'u3_ph2',
        letterSound: 'u',
        word: 'Sunday',
        phonetic: '/ˈsʌn.deɪ/',
        sentence: 'I do housework on Sundays.',
        translation: 'Mình làm việc nhà vào các ngày Chủ Nhật.',
        tip: 'Chữ cái "u" trong "Sunday" phát âm là âm ngắn /ʌ/.',
      },
    ],
    reading: {
      id: 'u3_r1',
      title: "Nam's Week (Trang 27 - SGK)",
      unitId: 3,
      imageTheme: 'calendar_week',
      passageEn: 'I am Nam. It is Monday today. It is a school day. I go to school on Mondays, Tuesdays, Wednesdays, Thursdays and Fridays. At the weekend, I stay at home. I do housework on Saturdays. I watch TV on Sundays. What do you do at the weekend?',
      passageVi: 'Mình là Nam. Hôm nay là thứ Hai. Hôm nay là một ngày đi học. Mình đi học vào các ngày thứ Hai, thứ Ba, thứ Tư, thứ Năm và thứ Sáu. Vào cuối tuần, mình ở nhà. Mình làm việc nhà vào thứ Bảy. Mình xem TV vào Chủ Nhật. Bạn làm gì vào cuối tuần?',
      questions: [
        {
          id: 'u3_rq1',
          question: 'What day is it today in the story? (Hôm nay là thứ mấy trong bài?)',
          options: ['It is Sunday.', 'It is Monday.', 'It is Friday.', 'It is Saturday.'],
          correctIndex: 1,
          explanation: 'Trong bài viết: "It is Monday today."',
        },
        {
          id: 'u3_rq2',
          question: 'When does Nam go to school? (Nam đi học vào những ngày nào?)',
          options: ['Only on Mondays', 'On Saturdays and Sundays', 'From Mondays to Fridays', 'On the weekend'],
          correctIndex: 2,
          explanation: 'Trong bài: "I go to school on Mondays, Tuesdays, Wednesdays, Thursdays and Fridays."',
        },
        {
          id: 'u3_rq3',
          question: 'What does Nam do on Saturdays? (Nam làm gì vào thứ Bảy?)',
          options: ['He goes to school.', 'He plays football.', 'He does housework.', 'He watches TV.'],
          correctIndex: 2,
          explanation: 'Trong bài: "I do housework on Saturdays."',
        },
        {
          id: 'u3_rq4',
          question: 'What does Nam do on Sundays? (Nam làm gì vào Chủ Nhật?)',
          options: ['He watches TV.', 'He does homework.', 'He listens to music.', 'He goes swimming.'],
          correctIndex: 0,
          explanation: 'Trong bài: "I watch TV on Sundays."',
        },
      ],
    },
  },
  {
    id: 4,
    title: 'Unit 4: My Birthday Party',
    subtitleVi: 'Tiệc sinh nhật, các tháng & Đồ ăn, thức uống',
    themeColor: 'from-fuchsia-600 to-purple-700',
    icon: '🎂',
    grammar: [
      {
        id: 'u4_g1',
        title: 'Hỏi ngày sinh nhật vào tháng nào (When is your birthday?)',
        pattern: "When's your birthday? - It's in + [Tháng trong năm].",
        explanation: 'Dùng để hỏi xem sinh nhật của một người bạn rơi vào tháng mấy.',
        examples: [
          { q: "When's your birthday?", a: "It's in May.", meaning: 'Sinh nhật của bạn khi nào? - Vào tháng Năm.' },
          { q: "When's your birthday?", a: "It's in January.", meaning: 'Sinh nhật của bạn khi nào? - Vào tháng Một.' },
        ],
        zeraTip: '💡 Luôn dùng giới từ "in" trước tháng trong năm (ví dụ: in March, in December)!',
      },
      {
        id: 'u4_g2',
        title: 'Hỏi bạn muốn ăn hay uống gì (What do you want to eat/drink?)',
        pattern: 'What do you want to eat / drink? - I want some + [đồ ăn / thức uống].',
        explanation: 'Dùng trong bữa tiệc sinh nhật để mời bạn chọn đồ ăn hoặc đồ uống.',
        examples: [
          { q: 'What do you want to eat?', a: 'I want some chips.', meaning: 'Bạn muốn ăn gì? - Mình muốn một ít khoai tây chiên.' },
          { q: 'What do you want to drink?', a: 'I want some juice / water.', meaning: 'Bạn muốn uống gì? - Mình muốn một ít nước hoa quả / nước lọc.' },
        ],
        zeraTip: '💡 Dùng từ "some" (một ít/một vài) trước đồ ăn và thức uống nhé!',
      },
    ],
    coreVocab: [
      { id: 'u4_v1', word: 'January', phonetic: '/ˈdʒæn.ju.ə.ri/', meaningVi: 'tháng Một', partOfSpeech: 'n', exampleEn: "My birthday is in January.", exampleVi: 'Sinh nhật tớ vào tháng Một.', category: 'Các tháng' },
      { id: 'u4_v2', word: 'February', phonetic: '/ˈfeb.ru.ə.ri/', meaningVi: 'tháng Hai', partOfSpeech: 'n', exampleEn: "It's in February.", exampleVi: 'Sinh nhật vào tháng Hai.', category: 'Các tháng' },
      { id: 'u4_v3', word: 'March', phonetic: '/mɑːtʃ/', meaningVi: 'tháng Ba', partOfSpeech: 'n', exampleEn: "Bill's birthday is in March.", exampleVi: 'Sinh nhật của Bill vào tháng Ba.', category: 'Các tháng' },
      { id: 'u4_v4', word: 'April', phonetic: '/ˈeɪ.prəl/', meaningVi: 'tháng Tư', partOfSpeech: 'n', exampleEn: "Her party is in April.", exampleVi: 'Bữa tiệc của bạn ấy vào tháng Tư.', category: 'Các tháng' },
      { id: 'u4_v5', word: 'chips', phonetic: '/tʃɪps/', meaningVi: 'khoai tây chiên', partOfSpeech: 'n', exampleEn: 'I want some chips.', exampleVi: 'Tớ muốn một ít khoai tây chiên.', category: 'Đồ ăn' },
      { id: 'u4_v6', word: 'grapes', phonetic: '/ɡreɪps/', meaningVi: 'những quả nho', partOfSpeech: 'n', exampleEn: 'I want some grapes.', exampleVi: 'Tớ muốn ăn một ít nho.', category: 'Đồ ăn' },
      { id: 'u4_v7', word: 'jam', phonetic: '/dʒæm/', meaningVi: 'mứt hoa quả', partOfSpeech: 'n', exampleEn: 'I like jam on bread.', exampleVi: 'Tớ thích mứt phết bánh mì.', category: 'Đồ ăn' },
      { id: 'u4_v8', word: 'lemonade', phonetic: '/ˌlem.əˈneɪd/', meaningVi: 'nước chanh', partOfSpeech: 'n', exampleEn: 'I want some lemonade.', exampleVi: 'Tớ muốn uống nước chanh.', category: 'Đồ uống' },
      { id: 'u4_v9', word: 'water', phonetic: '/ˈwɔː.tər/', meaningVi: 'nước lọc', partOfSpeech: 'n', exampleEn: 'Can I have some water?', exampleVi: 'Cho mình xin một ít nước lọc nhé.', category: 'Đồ uống' },
    ],
    extendedVocab: [
      { id: 'u4_ev1', word: 'birthday cake', phonetic: '/ˈbɜːθ.deɪ keɪk/', meaningVi: 'bánh sinh nhật', partOfSpeech: 'n', exampleEn: 'The birthday cake is sweet.', exampleVi: 'Bánh sinh nhật rất ngọt ngào.', isExtended: true, category: 'Mở rộng: Sinh nhật' },
      { id: 'u4_ev2', word: 'candle', phonetic: '/ˈkæn.dəl/', meaningVi: 'cây nến', partOfSpeech: 'n', exampleEn: 'Blow out the candles!', exampleVi: 'Hãy thổi nến nào!', isExtended: true, category: 'Mở rộng: Sinh nhật' },
      { id: 'u4_ev3', word: 'orange juice', phonetic: '/ˈɒr.ɪndʒ dʒuːs/', meaningVi: 'nước cam ép', partOfSpeech: 'n', exampleEn: 'I want some orange juice.', exampleVi: 'Tớ muốn uống nước cam.', isExtended: true, category: 'Mở rộng: Đồ uống' },
      { id: 'u4_ev4', word: 'pizza', phonetic: '/ˈpiːt.sə/', meaningVi: 'bánh pi-da', partOfSpeech: 'n', exampleEn: 'We eat delicious pizza at the party.', exampleVi: 'Chúng tớ ăn bánh pizza ngon tuyệt ở bữa tiệc.', isExtended: true, category: 'Mở rộng: Đồ ăn' },
    ],
    communication: [
      {
        id: 'u4_c1',
        type: 'answer_to_question',
        instruction: 'Cho câu trả lời, hãy chọn câu hỏi tương ứng:',
        givenLabel: 'Câu trả lời của bạn Lucy:',
        prompt: "It's in May.",
        targetLabel: 'Câu hỏi của bạn Nam là:',
        options: [
          'What do you want to eat?',
          "When's your birthday?",
          'Where is your school?',
          'What time is it?',
        ],
        correctIndex: 1,
        explanation: 'Lucy trả lời thời điểm tháng sinh nhật "It\'s in May", câu hỏi là "When\'s your birthday?".',
      },
      {
        id: 'u4_c2',
        type: 'answer_to_question',
        instruction: 'Cho câu trả lời, hãy chọn câu hỏi thích hợp:',
        givenLabel: 'Câu trả lời của bạn Mary:',
        prompt: 'I want some lemonade and chips.',
        targetLabel: 'Câu hỏi của bạn chủ tiệc là:',
        options: [
          'What do you want to eat and drink?',
          'What time do you get up?',
          'Can you swim?',
          'What day is it today?',
        ],
        correctIndex: 0,
        explanation: 'Mary nói món mình muốn ăn và uống ("lemonade and chips"), câu hỏi là "What do you want to eat and drink?".',
      },
    ],
    phonics: [
      {
        id: 'u4_ph1',
        letterSound: 'j',
        word: 'jam',
        phonetic: '/dʒæm/',
        sentence: 'I like jam.',
        translation: 'Mình thích mứt.',
        tip: 'Âm /dʒ/ bật hơi tròn môi và rung nhẹ cổ họng.',
      },
      {
        id: 'u4_ph2',
        letterSound: 'w',
        word: 'water',
        phonetic: '/ˈwɔː.tər/',
        sentence: 'I want some water.',
        translation: 'Mình muốn một ít nước lọc.',
        tip: 'Âm /w/ chu môi tròn như khi huýt sáo rồi mở rộng miệng phát âm.',
      },
    ],
    reading: {
      id: 'u4_r1',
      title: "Bill's Birthday Letter (Trang 33 - SGK)",
      unitId: 4,
      imageTheme: 'birthday_party',
      passageEn: "Dear pen friend, My name's Bill. I'm from Britain. I'm nine years old. My birthday's in March. It's coming soon. I want some chips and some lemonade at my party. What about you? When's your birthday? What do you want to eat and drink at your party? Write to me soon. Bill",
      passageVi: 'Gửi người bạn qua thư, Tên mình là Bill. Mình đến từ nước Anh. Mình chín tuổi. Sinh nhật của mình vào tháng Ba. Nó sắp tới rồi. Mình muốn có một ít khoai tây chiên và nước chanh trong bữa tiệc của mình. Còn bạn thì sao? Sinh nhật của bạn khi nào? Bạn muốn ăn và uống gì trong bữa tiệc của mình? Viết thư lại cho mình sớm nhé. Bill',
      questions: [
        {
          id: 'u4_rq1',
          question: 'Where is Bill from? (Bill đến từ đâu?)',
          options: ['America', 'Britain', 'Australia', 'Viet Nam'],
          correctIndex: 1,
          explanation: 'Trong bức thư: "I\'m from Britain."',
        },
        {
          id: 'u4_rq2',
          question: "When is Bill's birthday? (Sinh nhật của Bill vào tháng mấy?)",
          options: ['March', 'January', 'April', 'May'],
          correctIndex: 0,
          explanation: 'Trong bài viết: "My birthday\'s in March."',
        },
        {
          id: 'u4_rq3',
          question: 'What does Bill want to eat at his party? (Bill muốn ăn gì?)',
          options: ['Chips', 'Grapes', 'Jam', 'Bread'],
          correctIndex: 0,
          explanation: 'Trong bài: "I want some chips and some lemonade". Chips là đồ ăn!',
        },
        {
          id: 'u4_rq4',
          question: 'What does Bill want to drink at his party? (Bill muốn uống gì?)',
          options: ['Water', 'Lemonade', 'Milk', 'Juice'],
          correctIndex: 1,
          explanation: 'Trong bài: "and some lemonade at my party."',
        },
      ],
    },
  },
  {
    id: 5,
    title: 'Unit 5: Things We Can Do',
    subtitleVi: 'Tài năng & Những điều chúng mình có thể làm',
    themeColor: 'from-violet-700 to-purple-900',
    icon: '🚴',
    grammar: [
      {
        id: 'u5_g1',
        title: 'Hỏi về khả năng của bạn (Can you...?)',
        pattern: 'Can you + [hành động]? - Yes, I can. / No, I cannot (can\'t).',
        explanation: 'Dùng để hỏi xem ai đó có biết làm hoặc có thể làm được việc gì không.',
        examples: [
          { q: 'Can you ride a bike?', a: 'Yes, I can.', meaning: 'Bạn có biết đi xe đạp không? - Có, mình biết đi.' },
          { q: 'Can you ride a horse?', a: "No, I can't.", meaning: 'Bạn có biết cưỡi ngựa không? - Không, mình không biết.' },
        ],
        zeraTip: '💡 "can\'t" là viết tắt của "cannot". Chú ý khi phát âm để người nghe phân biệt được can và can\'t nhé!',
      },
      {
        id: 'u5_g2',
        title: 'Hỏi về khả năng của bạn khác (Can he/she...?)',
        pattern: "Can he/she + [hành động]? - Yes, he/she can. / No, he/she can't, but he/she can + [hành động khác].",
        explanation: 'Dùng để hỏi xem một bạn nam hoặc nữ có thể làm việc gì không.',
        examples: [
          { q: 'Can she cook?', a: 'Yes, she can.', meaning: 'Cô ấy có biết nấu ăn không? - Có, bạn ấy biết.' },
          { q: 'Can he draw?', a: "No, he can't, but he can swim.", meaning: 'Cậu ấy có biết vẽ không? - Không, nhưng cậu ấy biết bơi.' },
        ],
        zeraTip: '💡 Cụm "but he/she can..." dùng để nối khi bạn ấy không làm được việc này nhưng lại giỏi việc khác!',
      },
    ],
    coreVocab: [
      { id: 'u5_v1', word: 'ride a bike', phonetic: '/raɪd ə baɪk/', meaningVi: 'đi xe đạp', partOfSpeech: 'phrase', exampleEn: 'I can ride a bike.', exampleVi: 'Tớ có thể đi xe đạp.', category: 'Kỹ năng' },
      { id: 'u5_v2', word: 'ride a horse', phonetic: '/raɪd ə hɔːs/', meaningVi: 'cưỡi ngựa', partOfSpeech: 'phrase', exampleEn: 'He cannot ride a horse.', exampleVi: 'Cậu ấy không biết cưỡi ngựa.', category: 'Kỹ năng' },
      { id: 'u5_v3', word: 'play the piano', phonetic: '/pleɪ ðə piˈæn.əʊ/', meaningVi: 'chơi đàn dương cầm (piano)', partOfSpeech: 'phrase', exampleEn: 'She can play the piano.', exampleVi: 'Cô ấy biết chơi đàn piano.', category: 'Nhạc cụ' },
      { id: 'u5_v4', word: 'play the guitar', phonetic: '/pleɪ ðə ɡɪˈtɑːr/', meaningVi: 'chơi đàn ghi-ta', partOfSpeech: 'phrase', exampleEn: 'Can you play the guitar?', exampleVi: 'Bạn có biết chơi đàn ghi-ta không?', category: 'Nhạc cụ' },
      { id: 'u5_v5', word: 'swim', phonetic: '/swɪm/', meaningVi: 'bơi lội', partOfSpeech: 'v', exampleEn: 'I can swim very well.', exampleVi: 'Tớ có thể bơi rất giỏi.', category: 'Thể thao' },
      { id: 'u5_v6', word: 'roller skate', phonetic: '/ˈrəʊ.lə skeɪt/', meaningVi: 'trượt pa-tanh', partOfSpeech: 'v', exampleEn: 'They can roller skate.', exampleVi: 'Họ có thể trượt pa-tanh.', category: 'Thể thao' },
      { id: 'u5_v7', word: 'cook', phonetic: '/kʊk/', meaningVi: 'nấu ăn', partOfSpeech: 'v', exampleEn: 'Can she cook? Yes, she can.', exampleVi: 'Cô ấy có biết nấu ăn không? Có, cô ấy biết.', category: 'Kỹ năng sống' },
      { id: 'u5_v8', word: 'draw', phonetic: '/drɔː/', meaningVi: 'vẽ tranh', partOfSpeech: 'v', exampleEn: 'I can draw a cat.', exampleVi: 'Tớ có thể vẽ một chú mèo.', category: 'Nghệ thuật' },
    ],
    extendedVocab: [
      { id: 'u5_ev1', word: 'fly a kite', phonetic: '/flaɪ ə kaɪt/', meaningVi: 'thả diều', partOfSpeech: 'phrase', exampleEn: 'We can fly a kite in the park.', exampleVi: 'Chúng mình có thể thả diều ở công viên.', isExtended: true, category: 'Mở rộng: Trò chơi' },
      { id: 'u5_ev2', word: 'skip', phonetic: '/skɪp/', meaningVi: 'nhảy dây', partOfSpeech: 'v', exampleEn: 'The girls can skip rope.', exampleVi: 'Các bạn nữ có thể nhảy dây.', isExtended: true, category: 'Mở rộng: Thể thao' },
      { id: 'u5_ev3', word: 'play badminton', phonetic: '/pleɪ ˈbæd.mɪn.tən/', meaningVi: 'chơi cầu lông', partOfSpeech: 'phrase', exampleEn: 'Can you play badminton?', exampleVi: 'Bạn có biết chơi cầu lông không?', isExtended: true, category: 'Mở rộng: Thể thao' },
      { id: 'u5_ev4', word: 'sing and dance', phonetic: '/sɪŋ ænd dɑːns/', meaningVi: 'hát và khiêu vũ', partOfSpeech: 'phrase', exampleEn: 'She can sing and dance.', exampleVi: 'Cô ấy có thể vừa hát vừa nhảy múa.', isExtended: true, category: 'Mở rộng: Nghệ thuật' },
    ],
    communication: [
      {
        id: 'u5_c1',
        type: 'answer_to_question',
        instruction: 'Cho câu trả lời, hãy chọn câu hỏi tương ứng:',
        givenLabel: 'Câu trả lời của bạn Mai:',
        prompt: 'Yes, I can. I can play the piano.',
        targetLabel: 'Câu hỏi của bạn Ben là:',
        options: [
          'Can you play the piano?',
          'What time do you get up?',
          'Where is your school?',
          'When is your birthday?',
        ],
        correctIndex: 0,
        explanation: 'Mai trả lời khẳng định về việc chơi piano "Yes, I can. I can play the piano", câu hỏi là "Can you play the piano?".',
      },
      {
        id: 'u5_c2',
        type: 'answer_to_question',
        instruction: 'Cho câu trả lời, hãy chọn câu hỏi đúng:',
        givenLabel: 'Câu trả lời của bạn thầy giáo:',
        prompt: "No, she can't, but she can swim.",
        targetLabel: 'Câu hỏi của bạn học sinh là:',
        options: [
          'Can she play football?',
          'Can he play football?',
          'Where is she from?',
          'What is her name?',
        ],
        correctIndex: 0,
        explanation: 'Câu trả lời bắt đầu bằng "No, she can\'t...", nên câu hỏi phải hỏi về một bạn nữ: "Can she play football?".',
      },
    ],
    phonics: [
      {
        id: 'u5_ph1',
        letterSound: 'y',
        word: 'yes',
        phonetic: '/jes/',
        sentence: 'Can you draw? - Yes, I can.',
        translation: 'Bạn có biết vẽ không? - Có, mình biết.',
        tip: 'Âm /j/ đọc lướt nhanh như âm "i" ngắn trong tiếng Việt.',
      },
      {
        id: 'u5_ph2',
        letterSound: 'n',
        word: 'no',
        phonetic: '/nəʊ/',
        sentence: "Can she swim? - No, she can't.",
        translation: 'Bạn ấy có biết bơi không? - Không, bạn ấy không biết.',
        tip: 'Âm /n/ là âm mũi, đầu lưỡi chạm vào chân răng hàm trên.',
      },
    ],
    reading: {
      id: 'u5_r1',
      title: 'Our School Club Survey (Trang 39 - SGK)',
      unitId: 5,
      imageTheme: 'sports_music_club',
      passageEn: 'I have three friends, Ha, Khoa and Rosie. Ha can play badminton, but she cannot swim. Khoa can ride a bike, but he cannot ride a horse. Rosie can play the piano, but she cannot play the guitar. I can sing, but I cannot dance. We can all roller skate.',
      passageVi: 'Mình có ba người bạn là Hà, Khoa và Rosie. Hà có thể chơi cầu lông, nhưng bạn ấy không biết bơi. Khoa có thể đi xe đạp, nhưng bạn ấy không biết cưỡi ngựa. Rosie có thể chơi piano, nhưng bạn ấy không biết chơi ghi-ta. Mình có thể hát, nhưng mình không biết nhảy múa. Tất cả chúng mình đều biết trượt pa-tanh.',
      questions: [
        {
          id: 'u5_rq1',
          question: 'Can Ha swim? (Hà có biết bơi không?)',
          options: ['Yes, she can.', "No, she can't.", 'She can ride a horse.', 'Yes, she does.'],
          correctIndex: 1,
          explanation: 'Trong bài viết: "Ha can play badminton, but she cannot swim."',
        },
        {
          id: 'u5_rq2',
          question: 'What can Khoa do? (Khoa có thể làm gì?)',
          options: ['Ride a horse', 'Ride a bike', 'Play the guitar', 'Cook'],
          correctIndex: 1,
          explanation: 'Trong bài: "Khoa can ride a bike, but he cannot ride a horse."',
        },
        {
          id: 'u5_rq3',
          question: 'Can Rosie play the piano? (Rosie có biết chơi piano không?)',
          options: ['No, she cannot.', 'Yes, she can.', 'She can play guitar.', 'No, he cannot.'],
          correctIndex: 1,
          explanation: 'Trong bài: "Rosie can play the piano, but she cannot play the guitar."',
        },
        {
          id: 'u5_rq4',
          question: 'What can they all do together? (Tất cả các bạn đều biết làm gì?)',
          options: ['Sing', 'Dance', 'Roller skate', 'Play badminton'],
          correctIndex: 2,
          explanation: 'Trong bài: "We can all roller skate."',
        },
      ],
    },
  },
  {
    id: 6,
    title: 'Unit 6: Our School Facilities',
    subtitleVi: 'Khuôn viên trường học & Cơ sở vật chất',
    themeColor: 'from-purple-600 to-indigo-700',
    icon: '🏫',
    grammar: [
      {
        id: 'u6_g1',
        title: 'Hỏi trường học của bạn ở đâu (Where is your school?)',
        pattern: 'Where is your school? - It is in the + [city / mountains / town / village].',
        explanation: 'Dùng để hỏi vị trí trường học của bạn nằm ở đâu.',
        examples: [
          { q: "Where's your school?", a: "It's in the city.", meaning: 'Trường của bạn ở đâu? - Trường ở thành phố.' },
          { q: "Where's your school?", a: "It's in the mountains.", meaning: 'Trường của bạn ở đâu? - Trường ở vùng núi.' },
        ],
        zeraTip: '💡 Nhớ có mạo từ "the" trước các danh từ chỉ khu vực: in the city, in the village, in the town, in the mountains!',
      },
      {
        id: 'u6_g2',
        title: 'Hỏi số lượng cơ sở vật chất ở trường (How many ... are there...?)',
        pattern: 'How many + [danh từ số nhiều] are there at your school? - There is one... / There are two / three...',
        explanation: 'Dùng để hỏi trường có bao nhiêu tòa nhà, phòng máy tính, sân chơi hay khu vườn.',
        examples: [
          { q: 'How many buildings are there at your school?', a: 'There are three.', meaning: 'Có bao nhiêu tòa nhà ở trường bạn? - Có ba tòa nhà.' },
          { q: 'How many playgrounds are there at your school?', a: 'There is one.', meaning: 'Có bao nhiêu sân chơi ở trường bạn? - Có một sân chơi.' },
        ],
        zeraTip: '💡 Có 1 thì dùng "There is one". Có từ 2 trở lên thì dùng "There are" nhé!',
      },
    ],
    coreVocab: [
      { id: 'u6_v1', word: 'city', phonetic: '/ˈsɪt.i/', meaningVi: 'thành phố', partOfSpeech: 'n', exampleEn: "My school is in the city.", exampleVi: 'Trường của tớ ở thành phố.', category: 'Địa điểm' },
      { id: 'u6_v2', word: 'mountains', phonetic: '/ˈmaʊn.tɪnz/', meaningVi: 'vùng núi, những dãy núi', partOfSpeech: 'n', exampleEn: "His school is in the mountains.", exampleVi: 'Trường bạn ấy ở vùng núi.', category: 'Địa điểm' },
      { id: 'u6_v3', word: 'town', phonetic: '/taʊn/', meaningVi: 'thị trấn', partOfSpeech: 'n', exampleEn: "It's in the town.", exampleVi: 'Nó ở thị trấn.', category: 'Địa điểm' },
      { id: 'u6_v4', word: 'village', phonetic: '/ˈvɪl.ɪdʒ/', meaningVi: 'ngôi làng, miền quê', partOfSpeech: 'n', exampleEn: "Our school is in the village.", exampleVi: 'Trường chúng tớ ở trong làng.', category: 'Địa điểm' },
      { id: 'u6_v5', word: 'building', phonetic: '/ˈbɪl.dɪŋ/', meaningVi: 'tòa nhà', partOfSpeech: 'n', exampleEn: 'There are three buildings.', exampleVi: 'Có ba tòa nhà.', category: 'Cơ sở vật chất' },
      { id: 'u6_v6', word: 'computer room', phonetic: '/kəmˈpjuː.tə ruːm/', meaningVi: 'phòng máy tính', partOfSpeech: 'n', exampleEn: 'There are two computer rooms.', exampleVi: 'Có hai phòng máy tính.', category: 'Cơ sở vật chất' },
      { id: 'u6_v7', word: 'garden', phonetic: '/ˈɡɑː.dən/', meaningVi: 'khu vườn trường', partOfSpeech: 'n', exampleEn: 'There is one garden with flowers.', exampleVi: 'Có một khu vườn với nhiều hoa.', category: 'Cơ sở vật chất' },
      { id: 'u6_v8', word: 'playground', phonetic: '/ˈpleɪ.ɡraʊnd/', meaningVi: 'sân chơi', partOfSpeech: 'n', exampleEn: 'The playground is very big.', exampleVi: 'Sân chơi rất rộng rãi.', category: 'Cơ sở vật chất' },
    ],
    extendedVocab: [
      { id: 'u6_ev1', word: 'library', phonetic: '/ˈlaɪ.brər.i/', meaningVi: 'thư viện', partOfSpeech: 'n', exampleEn: 'We read books in the school library.', exampleVi: 'Chúng tớ đọc sách ở thư viện trường.', isExtended: true, category: 'Mở rộng: Cơ sở trường' },
      { id: 'u6_ev2', word: 'canteen', phonetic: '/kænˈtiːn/', meaningVi: 'căng-tin trường học', partOfSpeech: 'n', exampleEn: 'We buy snacks at the canteen.', exampleVi: 'Chúng tớ mua đồ ăn nhẹ ở căng-tin.', isExtended: true, category: 'Mở rộng: Cơ sở trường' },
      { id: 'u6_ev3', word: 'swimming pool', phonetic: '/ˈswɪm.ɪŋ puːl/', meaningVi: 'bể bơi', partOfSpeech: 'n', exampleEn: 'Our school has a nice swimming pool.', exampleVi: 'Trường tớ có một bể bơi đẹp.', isExtended: true, category: 'Mở rộng: Cơ sở trường' },
      { id: 'u6_ev4', word: 'art room', phonetic: '/ɑːt ruːm/', meaningVi: 'phòng học Mỹ thuật', partOfSpeech: 'n', exampleEn: 'We paint pictures in the art room.', exampleVi: 'Chúng tớ vẽ tranh trong phòng mỹ thuật.', isExtended: true, category: 'Mở rộng: Cơ sở trường' },
    ],
    communication: [
      {
        id: 'u6_c1',
        type: 'answer_to_question',
        instruction: 'Cho câu trả lời, hãy chọn câu hỏi phù hợp nhất:',
        givenLabel: 'Câu trả lời của bạn Lucy:',
        prompt: "It's in the city.",
        targetLabel: 'Câu hỏi của bạn Minh là:',
        options: [
          'Where is your school?',
          'What time do you go to school?',
          'How many buildings are there?',
          'Can you swim?',
        ],
        correctIndex: 0,
        explanation: 'Lucy trả lời vị trí trường ở thành phố "It\'s in the city", câu hỏi là "Where is your school?".',
      },
      {
        id: 'u6_c2',
        type: 'answer_to_question',
        instruction: 'Cho câu trả lời, hãy chọn câu hỏi tương ứng:',
        givenLabel: 'Câu trả lời của bạn Bill:',
        prompt: 'There are two computer rooms.',
        targetLabel: 'Câu hỏi của bạn Mai là:',
        options: [
          'How many computer rooms are there at your school?',
          'Where is your school?',
          'When is your sports day?',
          'What day is it today?',
        ],
        correctIndex: 0,
        explanation: 'Trả lời số lượng "There are two computer rooms", câu hỏi bắt đầu bằng "How many computer rooms are there at your school?".',
      },
    ],
    phonics: [
      {
        id: 'u6_ph1',
        letterSound: 's',
        word: 'mountains',
        phonetic: '/ˈmaʊn.tɪnz/',
        sentence: 'My school is in the mountains.',
        translation: 'Trường mình ở vùng núi.',
        tip: 'Chữ cái "s" đứng sau nguyên âm/phụ âm rung đọc là âm /z/.',
      },
      {
        id: 'u6_ph2',
        letterSound: 'es',
        word: 'villages',
        phonetic: '/ˈvɪl.ɪ.dʒɪz/',
        sentence: 'There are three villages near my school.',
        translation: 'Có ba ngôi làng gần trường của mình.',
        tip: 'Đuôi -es sau âm /dʒ/ đọc là /ɪz/.',
      },
    ],
    reading: {
      id: 'u6_r1',
      title: 'Our Village School (Trang 49 - SGK)',
      unitId: 6,
      imageTheme: 'village_school',
      passageEn: 'Our school is big. It is in the village. There are three buildings and a garden at our school. The garden has many trees and flowers. There is a big playground. We can play football, badminton and volleyball there. I love my school!',
      passageVi: 'Trường của chúng mình rất lớn. Trường nằm ở trong làng. Có ba tòa nhà và một khu vườn ở trường chúng mình. Khu vườn có rất nhiều cây và hoa. Có một sân chơi lớn. Chúng mình có thể chơi bóng đá, cầu lông và bóng chuyền ở đó. Mình rất yêu trường mình!',
      questions: [
        {
          id: 'u6_rq1',
          question: 'Where is the school? (Trường học nằm ở đâu?)',
          options: ['In the city', 'In the village', 'In the mountains', 'In the town'],
          correctIndex: 1,
          explanation: 'Trong bài viết: "It is in the village."',
        },
        {
          id: 'u6_rq2',
          question: 'How many buildings are there at the school? (Có bao nhiêu tòa nhà?)',
          options: ['One', 'Two', 'Three', 'Four'],
          correctIndex: 2,
          explanation: 'Trong bài viết: "There are three buildings".',
        },
        {
          id: 'u6_rq3',
          question: 'What does the garden have? (Khu vườn có những gì?)',
          options: ['Many cars', 'Many trees and flowers', 'Computers', 'A swimming pool'],
          correctIndex: 1,
          explanation: 'Trong bài: "The garden has many trees and flowers."',
        },
        {
          id: 'u6_rq4',
          question: 'What can pupils play in the playground? (Học sinh có thể chơi gì ở sân chơi?)',
          options: ['Piano and guitar', 'Football, badminton and volleyball', 'Ride a horse', 'Cook meals'],
          correctIndex: 1,
          explanation: 'Trong bài: "We can play football, badminton and volleyball there."',
        },
      ],
    },
  },
  {
    id: 7,
    title: 'Unit 7: Our Timetables',
    subtitleVi: 'Thời khóa biểu & Các môn học',
    themeColor: 'from-purple-700 to-violet-800',
    icon: '📚',
    grammar: [
      {
        id: 'u7_g1',
        title: 'Hỏi hôm nay bạn có những môn học nào (What subjects do you have today?)',
        pattern: 'What subjects do you have today? - I have + [Tên các môn học].',
        explanation: 'Dùng để hỏi và trả lời về các môn học theo thời khóa biểu ngày hôm đó.',
        examples: [
          { q: 'What subjects do you have today?', a: 'I have Vietnamese and English.', meaning: 'Hôm nay bạn có những môn gì? - Mình có môn Tiếng Việt và Tiếng Anh.' },
          { q: 'What subjects do you have today?', a: 'I have maths, science and art.', meaning: 'Hôm nay bạn có những môn gì? - Mình có Toán, Khoa học và Mỹ thuật.' },
        ],
        zeraTip: '💡 "maths" có chữ "s" ở cuối là từ chuẩn theo Anh - Anh nhé!',
      },
      {
        id: 'u7_g2',
        title: 'Hỏi bạn có môn học nào vào ngày nào (When do you have...?)',
        pattern: 'When do you have + [Môn học]? - I have it on + [Thứ + s].',
        explanation: 'Dùng để hỏi lịch học của một môn học cụ thể trong tuần.',
        examples: [
          { q: 'When do you have maths?', a: 'I have it on Mondays and Fridays.', meaning: 'Khi nào bạn có môn Toán? - Mình có vào các ngày thứ Hai và thứ Sáu.' },
          { q: 'When do you have music?', a: 'I have it on Wednesdays.', meaning: 'Khi nào bạn có môn Âm nhạc? - Mình có vào thứ Tư.' },
        ],
        zeraTip: '💡 Dùng đại từ "it" (nó) thay thế cho tên môn học đã được nhắc tới ở câu hỏi!',
      },
    ],
    coreVocab: [
      { id: 'u7_v1', word: 'Vietnamese', phonetic: '/ˌvjet.nəˈmiːz/', meaningVi: 'môn Tiếng Việt', partOfSpeech: 'n', exampleEn: 'I have Vietnamese today.', exampleVi: 'Hôm nay tớ có môn Tiếng Việt.', category: 'Môn học' },
      { id: 'u7_v2', word: 'English', phonetic: '/ˈɪŋ.ɡlɪʃ/', meaningVi: 'môn Tiếng Anh', partOfSpeech: 'n', exampleEn: 'I love English.', exampleVi: 'Tớ rất thích môn Tiếng Anh.', category: 'Môn học' },
      { id: 'u7_v3', word: 'maths', phonetic: '/mæθs/', meaningVi: 'môn Toán', partOfSpeech: 'n', exampleEn: 'I have maths every day.', exampleVi: 'Tớ có môn Toán mỗi ngày.', category: 'Môn học' },
      { id: 'u7_v4', word: 'science', phonetic: '/ˈsaɪ.əns/', meaningVi: 'môn Khoa học', partOfSpeech: 'n', exampleEn: 'We have science on Tuesdays.', exampleVi: 'Chúng tớ có môn Khoa học vào thứ Ba.', category: 'Môn học' },
      { id: 'u7_v5', word: 'art', phonetic: '/ɑːt/', meaningVi: 'môn Mỹ thuật', partOfSpeech: 'n', exampleEn: 'I draw pictures in art class.', exampleVi: 'Tớ vẽ tranh trong giờ mỹ thuật.', category: 'Môn học' },
      { id: 'u7_v6', word: 'music', phonetic: '/ˈmjuː.zɪk/', meaningVi: 'môn Âm nhạc', partOfSpeech: 'n', exampleEn: 'I sing songs in music.', exampleVi: 'Tớ hát các bài hát trong giờ âm nhạc.', category: 'Môn học' },
      { id: 'u7_v7', word: 'history and geography', phonetic: '/ˈhɪs.tər.i ænd dʒiˈɒɡ.rə.fi/', meaningVi: 'môn Lịch sử và Địa lí', partOfSpeech: 'n', exampleEn: 'I have history and geography on Fridays.', exampleVi: 'Tớ có Lịch sử và Địa lí vào thứ Sáu.', category: 'Môn học' },
    ],
    extendedVocab: [
      { id: 'u7_ev1', word: 'IT (Information Technology)', phonetic: '/ˌaɪˈtiː/', meaningVi: 'môn Tin học', partOfSpeech: 'n', exampleEn: 'I learn computers in IT class.', exampleVi: 'Tớ học máy tính trong giờ Tin học.', isExtended: true, category: 'Mở rộng: Môn học' },
      { id: 'u7_ev2', word: 'PE (Physical Education)', phonetic: '/ˌpiːˈiː/', meaningVi: 'môn Thể dục', partOfSpeech: 'n', exampleEn: 'We run and jump in PE.', exampleVi: 'Chúng tớ chạy và nhảy trong giờ Thể dục.', isExtended: true, category: 'Mở rộng: Môn học' },
      { id: 'u7_ev3', word: 'timetable', phonetic: '/ˈtaɪmˌteɪ.bəl/', meaningVi: 'thời khóa biểu', partOfSpeech: 'n', exampleEn: 'Look at our school timetable.', exampleVi: 'Hãy nhìn vào thời khóa biểu của trường chúng mình.', isExtended: true, category: 'Mở rộng: Trường học' },
      { id: 'u7_ev4', word: 'break time', phonetic: '/breɪk taɪm/', meaningVi: 'giờ ra chơi', partOfSpeech: 'n', exampleEn: 'We play in the yard at break time.', exampleVi: 'Chúng tớ chơi ở sân trường vào giờ ra chơi.', isExtended: true, category: 'Mở rộng: Trường học' },
    ],
    communication: [
      {
        id: 'u7_c1',
        type: 'answer_to_question',
        instruction: 'Cho câu trả lời, hãy chọn câu hỏi phù hợp nhất:',
        givenLabel: 'Câu trả lời của bạn Minh:',
        prompt: 'I have English and maths.',
        targetLabel: 'Câu hỏi của mẹ bạn Minh là:',
        options: [
          'What subjects do you have today?',
          'What time do you go to bed?',
          'Where are you from?',
          'Can you play the guitar?',
        ],
        correctIndex: 0,
        explanation: 'Minh kể tên các môn học mình có hôm nay, câu hỏi là "What subjects do you have today?".',
      },
      {
        id: 'u7_c2',
        type: 'answer_to_question',
        instruction: 'Cho câu trả lời, hãy chọn câu hỏi tương ứng:',
        givenLabel: 'Câu trả lời của bạn học sinh:',
        prompt: 'I have it on Mondays and Fridays.',
        targetLabel: 'Câu hỏi của bạn Lucy là:',
        options: [
          'When do you have science?',
          'What day is it today?',
          'How many buildings are there?',
          'When is your birthday?',
        ],
        correctIndex: 0,
        explanation: 'Câu trả lời nói về lịch học của môn ("I have it on..."), nên câu hỏi là "When do you have science?".',
      },
    ],
    phonics: [
      {
        id: 'u7_ph1',
        letterSound: 'se',
        word: 'Vietnamese',
        phonetic: '/ˌvjet.nəˈmiːz/',
        sentence: 'When do you have Vietnamese?',
        translation: 'Khi nào bạn có môn Tiếng Việt?',
        tip: 'Chữ cái "se" trong Vietnamese phát âm là âm /z/.',
      },
      {
        id: 'u7_ph2',
        letterSound: 'ce',
        word: 'science',
        phonetic: '/ˈsaɪ.əns/',
        sentence: 'We have science today.',
        translation: 'Chúng mình có môn Khoa học hôm nay.',
        tip: 'Chữ cái "ce" trong science phát âm là âm /s/.',
      },
    ],
    reading: {
      id: 'u7_r1',
      title: "Minh's School Timetable (Trang 55 - SGK)",
      unitId: 7,
      imageTheme: 'timetable_books',
      passageEn: 'My name is Minh. I go to school from Mondays to Fridays. I have Vietnamese and maths every school day. I have English on Mondays, Thursdays and Fridays. I have science on Wednesdays and Thursdays. I have music on Tuesdays. I like music very much.',
      passageVi: 'Tên mình là Minh. Mình đi học từ thứ Hai đến thứ Sáu. Mình có môn Tiếng Việt và Toán vào tất cả các ngày đi học. Mình có môn Tiếng Anh vào thứ Hai, thứ Năm và thứ Sáu. Mình có môn Khoa học vào thứ Tư và thứ Năm. Mình có môn Âm nhạc vào thứ Ba. Mình rất thích môn Âm nhạc.',
      questions: [
        {
          id: 'u7_rq1',
          question: 'What subjects does Minh have every school day? (Môn nào Minh học mỗi ngày?)',
          options: ['English and music', 'Vietnamese and maths', 'Science and art', 'Maths and IT'],
          correctIndex: 1,
          explanation: 'Trong bài viết: "I have Vietnamese and maths every school day."',
        },
        {
          id: 'u7_rq2',
          question: 'When does Minh have English? (Minh học Tiếng Anh khi nào?)',
          options: ['Tuesdays and Wednesdays', 'Mondays, Thursdays and Fridays', 'Only on Fridays', 'At the weekend'],
          correctIndex: 1,
          explanation: 'Trong bài: "I have English on Mondays, Thursdays and Fridays."',
        },
        {
          id: 'u7_rq3',
          question: 'When does Minh have music? (Minh học Âm nhạc vào thứ mấy?)',
          options: ['On Tuesdays', 'On Wednesdays', 'On Thursdays', 'On Fridays'],
          correctIndex: 0,
          explanation: 'Trong bài: "I have music on Tuesdays."',
        },
        {
          id: 'u7_rq4',
          question: 'Which subject does Minh like very much? (Minh rất thích môn gì?)',
          options: ['Maths', 'Science', 'Music', 'History'],
          correctIndex: 2,
          explanation: 'Trong bài: "I like music very much."',
        },
      ],
    },
  },
  {
    id: 8,
    title: 'Unit 8: My Favourite Subjects',
    subtitleVi: 'Môn học yêu thích & Ước mơ tương lai',
    themeColor: 'from-fuchsia-600 to-indigo-800',
    icon: '🎨',
    grammar: [
      {
        id: 'u8_g1',
        title: 'Hỏi môn học yêu thích (What is your favourite subject?)',
        pattern: "What's your favourite subject? - It's + [Tên môn học].",
        explanation: 'Dùng để hỏi xem ai đó thích nhất môn học nào.',
        examples: [
          { q: "What's your favourite subject?", a: "It's art.", meaning: 'Môn học yêu thích của bạn là gì? - Đó là môn Mỹ thuật.' },
          { q: "What's your favourite subject?", a: "It's English.", meaning: 'Môn học yêu thích của bạn là gì? - Đó là môn Tiếng Anh.' },
        ],
        zeraTip: '💡 "favourite" nghĩa là được yêu thích nhất. Bé hãy trả lời bằng niềm say mê của mình nhé!',
      },
      {
        id: 'u8_g2',
        title: 'Hỏi lý do thích môn học (Why do you like...?)',
        pattern: 'Why do you like + [Môn học]? - Because I want to be + [a / an + Nghề nghiệp].',
        explanation: 'Dùng để giải thích lý do vì sao thích môn học đó gắn với ước mơ nghề nghiệp tương lai.',
        examples: [
          { q: 'Why do you like English?', a: 'Because I want to be an English teacher.', meaning: 'Vì sao bạn thích Tiếng Anh? - Vì mình muốn trở thành cô giáo dạy Tiếng Anh.' },
          { q: 'Why do you like art?', a: 'Because I want to be a painter.', meaning: 'Vì sao bạn thích Mỹ thuật? - Vì mình muốn trở thành họa sĩ.' },
        ],
        zeraTip: '💡 Dùng "an" trước từ bắt đầu bằng nguyên âm: an English teacher, an artist. Dùng "a" trước phụ âm: a painter, a singer, a maths teacher!',
      },
    ],
    coreVocab: [
      { id: 'u8_v1', word: 'favourite', phonetic: '/ˈfeɪ.vər.ɪt/', meaningVi: 'yêu thích nhất', partOfSpeech: 'adj', exampleEn: "My favourite subject is art.", exampleVi: 'Môn học yêu thích của tớ là Mỹ thuật.', category: 'Sở thích' },
      { id: 'u8_v2', word: 'why', phonetic: '/waɪ/', meaningVi: 'tại sao, vì sao', partOfSpeech: 'adv', exampleEn: 'Why do you like music?', exampleVi: 'Tại sao bạn thích âm nhạc?', category: 'Từ hỏi' },
      { id: 'u8_v3', word: 'because', phonetic: '/bɪˈkɒz/', meaningVi: 'bởi vì', partOfSpeech: 'conj', exampleEn: 'Because I want to be a singer.', exampleVi: 'Bởi vì tớ muốn trở thành ca sĩ.', category: 'Liên từ' },
      { id: 'u8_v4', word: 'English teacher', phonetic: '/ˈɪŋ.ɡlɪʃ ˈtiː.tʃər/', meaningVi: 'giáo viên Tiếng Anh', partOfSpeech: 'n', exampleEn: 'I want to be an English teacher.', exampleVi: 'Tớ muốn làm giáo viên Tiếng Anh.', category: 'Nghề nghiệp' },
      { id: 'u8_v5', word: 'maths teacher', phonetic: '/mæθs ˈtiː.tʃər/', meaningVi: 'giáo viên dạy Toán', partOfSpeech: 'n', exampleEn: 'She wants to be a maths teacher.', exampleVi: 'Cô ấy muốn làm giáo viên Toán.', category: 'Nghề nghiệp' },
      { id: 'u8_v6', word: 'painter', phonetic: '/ˈpeɪn.tər/', meaningVi: 'họa sĩ', partOfSpeech: 'n', exampleEn: 'He paints pictures, he is a painter.', exampleVi: 'Cậu ấy vẽ tranh, cậu ấy là họa sĩ.', category: 'Nghề nghiệp' },
      { id: 'u8_v7', word: 'singer', phonetic: '/ˈsɪŋ.ər/', meaningVi: 'ca sĩ', partOfSpeech: 'n', exampleEn: 'I like music because I want to be a singer.', exampleVi: 'Tớ thích âm nhạc vì tớ muốn làm ca sĩ.', category: 'Nghề nghiệp' },
    ],
    extendedVocab: [
      { id: 'u8_ev1', word: 'doctor', phonetic: '/ˈdɒk.tər/', meaningVi: 'bác sĩ', partOfSpeech: 'n', exampleEn: 'I like science because I want to be a doctor.', exampleVi: 'Tớ thích khoa học vì tớ muốn làm bác sĩ.', isExtended: true, category: 'Mở rộng: Nghề nghiệp' },
      { id: 'u8_ev2', word: 'pilot', phonetic: '/ˈpaɪ.lət/', meaningVi: 'phi công', partOfSpeech: 'n', exampleEn: 'He wants to fly planes and be a pilot.', exampleVi: 'Cậu ấy muốn lái máy bay và làm phi công.', isExtended: true, category: 'Mở rộng: Nghề nghiệp' },
      { id: 'u8_ev3', word: 'scientist', phonetic: '/ˈsaɪən.tɪst/', meaningVi: 'nhà khoa học', partOfSpeech: 'n', exampleEn: 'She wants to be a great scientist.', exampleVi: 'Cô ấy muốn trở thành nhà khoa học tài ba.', isExtended: true, category: 'Mở rộng: Nghề nghiệp' },
      { id: 'u8_ev4', word: 'computer engineer', phonetic: '/kəmˈpjuː.tər ˌen.dʒɪˈnɪər/', meaningVi: 'kỹ sư máy tính / tin học', partOfSpeech: 'n', exampleEn: 'I like IT because I want to be an engineer.', exampleVi: 'Tớ thích môn Tin vì muốn làm kỹ sư máy tính.', isExtended: true, category: 'Mở rộng: Nghề nghiệp' },
    ],
    communication: [
      {
        id: 'u8_c1',
        type: 'answer_to_question',
        instruction: 'Cho câu trả lời, hãy chọn câu hỏi tương ứng:',
        givenLabel: 'Câu trả lời của bạn Mary:',
        prompt: "It's art. I like art very much.",
        targetLabel: 'Câu hỏi của bạn Bill là:',
        options: [
          "What's your favourite subject?",
          'Where is your school?',
          'What time do you get up?',
          'When is your birthday?',
        ],
        correctIndex: 0,
        explanation: 'Mary nói môn học yêu thích nhất là Mỹ thuật, nên câu hỏi là "What\'s your favourite subject?".',
      },
      {
        id: 'u8_c2',
        type: 'answer_to_question',
        instruction: 'Cho câu trả lời, hãy chọn câu hỏi thích hợp:',
        givenLabel: 'Câu trả lời của bạn Nam:',
        prompt: 'Because I want to be an English teacher.',
        targetLabel: 'Câu hỏi của bạn Linh là:',
        options: [
          'Why do you like English?',
          'Where is your school?',
          'How many teachers are there?',
          'What time is it?',
        ],
        correctIndex: 0,
        explanation: 'Nam trả lời lý do "Because I want to be an English teacher", câu hỏi bắt đầu bằng "Why do you like English?".',
      },
    ],
    phonics: [
      {
        id: 'u8_ph1',
        letterSound: 'ke',
        word: 'like',
        phonetic: '/laɪk/',
        sentence: 'I like English.',
        translation: 'Mình thích môn Tiếng Anh.',
        tip: 'Đuôi -ke phát âm là âm /k/ bật hơi nhẹ ở vòm họng.',
      },
      {
        id: 'u8_ph2',
        letterSound: 'te',
        word: 'write',
        phonetic: '/raɪt/',
        sentence: "Let's write a story.",
        translation: 'Chúng mình hãy cùng viết một câu chuyện nào.',
        tip: 'Đuôi -te phát âm là âm /t/ gọn gàng và dứt khoát.',
      },
    ],
    reading: {
      id: 'u8_r1',
      title: "Peter's Favourite Subjects and Dreams (Trang 61 - SGK)",
      unitId: 8,
      imageTheme: 'career_dreams',
      passageEn: 'My name is Peter. It is Thursday today. I have English, PE, music, art and maths at school. My favourite subject is English. I like it because I want to be an English teacher. I also like music because I want to be a singer too. I do not like maths because I am not good at it.',
      passageVi: 'Tên mình là Peter. Hôm nay là thứ Năm. Mình có môn Tiếng Anh, Thể dục, Âm nhạc, Mỹ thuật và Toán ở trường. Môn học yêu thích nhất của mình là Tiếng Anh. Mình thích môn này vì mình muốn trở thành giáo viên Tiếng Anh. Mình cũng thích âm nhạc vì mình muốn làm ca sĩ nữa. Mình không thích môn Toán vì mình học không giỏi môn này.',
      questions: [
        {
          id: 'u8_rq1',
          question: 'What day is it today in the passage? (Hôm nay là thứ mấy?)',
          options: ['Monday', 'Thursday', 'Friday', 'Sunday'],
          correctIndex: 1,
          explanation: 'Trong bài viết: "It is Thursday today."',
        },
        {
          id: 'u8_rq2',
          question: "What is Peter's favourite subject? (Môn học yêu thích nhất của Peter là gì?)",
          options: ['Maths', 'Music', 'English', 'Art'],
          correctIndex: 2,
          explanation: 'Trong bài: "My favourite subject is English."',
        },
        {
          id: 'u8_rq3',
          question: 'Why does Peter like English? (Tại sao Peter thích Tiếng Anh?)',
          options: [
            'Because he wants to be a painter.',
            'Because he wants to be an English teacher.',
            'Because he wants to be a singer.',
            'Because he likes maths.',
          ],
          correctIndex: 1,
          explanation: 'Trong bài: "because I want to be an English teacher."',
        },
        {
          id: 'u8_rq4',
          question: 'Why does Peter like music? (Tại sao bạn ấy thích âm nhạc?)',
          options: [
            'Because he wants to be a singer.',
            'Because he wants to be a doctor.',
            'Because he wants to play football.',
            'Because it is on Monday.',
          ],
          correctIndex: 0,
          explanation: 'Trong bài: "I also like music because I want to be a singer too."',
        },
      ],
    },
  },
  {
    id: 9,
    title: 'Unit 9: Our Sports Day',
    subtitleVi: 'Ngày hội thể thao của trường',
    themeColor: 'from-purple-600 to-violet-800',
    icon: '🏆',
    grammar: [
      {
        id: 'u9_g1',
        title: 'Hỏi ngày hội thể thao có vào tháng nào không (Is your sports day in...?)',
        pattern: "Is your sports day in + [Tháng]? - Yes, it is. / No, it isn't. It's in + [Tháng đúng].",
        explanation: 'Dùng để xác nhận xem ngày hội thể thao của trường diễn ra vào tháng mấy.',
        examples: [
          { q: 'Is your sports day in May?', a: 'Yes, it is.', meaning: 'Ngày hội thể thao trường bạn vào tháng Năm à? - Đúng rồi.' },
          { q: 'Is your sports day in May too?', a: "No, it isn't. It's in April.", meaning: 'Ngày hội thể thao trường bạn cũng vào tháng Năm à? - Không phải, vào tháng Tư.' },
        ],
        zeraTip: '💡 Trả lời khẳng định là "Yes, it is.", phủ định là "No, it isn\'t." nhé bé!',
      },
      {
        id: 'u9_g2',
        title: 'Hỏi khi nào diễn ra ngày hội thể thao (When is your sports day?)',
        pattern: "When's your sports day? - It's in + [Tháng trong năm].",
        explanation: 'Dùng để hỏi trực tiếp thời điểm tháng tổ chức ngày hội thể thao.',
        examples: [
          { q: "When's your sports day?", a: "It's in October.", meaning: 'Khi nào trường bạn tổ chức ngày hội thể thao? - Vào tháng Mười.' },
          { q: "When's your sports day?", a: "It's in November.", meaning: 'Khi nào trường bạn tổ chức ngày hội thể thao? - Vào tháng Mười Một.' },
        ],
        zeraTip: '💡 "sports day" có chữ "s" sau từ sport, thể hiện ngày hội có nhiều môn thể thao cùng thi đấu!',
      },
    ],
    coreVocab: [
      { id: 'u9_v1', word: 'sports day', phonetic: '/ˈspɔːts deɪ/', meaningVi: 'ngày hội thể thao', partOfSpeech: 'n', exampleEn: 'Our sports day is in November.', exampleVi: 'Ngày hội thể thao trường tớ vào tháng Mười Một.', category: 'Sự kiện trường' },
      { id: 'u9_v2', word: 'May', phonetic: '/meɪ/', meaningVi: 'tháng Năm', partOfSpeech: 'n', exampleEn: "It's in May.", exampleVi: 'Vào tháng Năm.', category: 'Các tháng' },
      { id: 'u9_v3', word: 'June', phonetic: '/dʒuːn/', meaningVi: 'tháng Sáu', partOfSpeech: 'n', exampleEn: 'School sports day is in June.', exampleVi: 'Ngày hội thể thao trường vào tháng Sáu.', category: 'Các tháng' },
      { id: 'u9_v4', word: 'July', phonetic: '/dʒuˈlaɪ/', meaningVi: 'tháng Bảy', partOfSpeech: 'n', exampleEn: "It is not in July.", exampleVi: 'Không phải vào tháng Bảy.', category: 'Các tháng' },
      { id: 'u9_v5', word: 'August', phonetic: '/ɔːˈɡʌst/', meaningVi: 'tháng Tám', partOfSpeech: 'n', exampleEn: 'We have holidays in August.', exampleVi: 'Chúng tớ nghỉ lễ vào tháng Tám.', category: 'Các tháng' },
      { id: 'u9_v6', word: 'September', phonetic: '/sepˈtem.bər/', meaningVi: 'tháng Chín', partOfSpeech: 'n', exampleEn: 'New school year begins in September.', exampleVi: 'Năm học mới bắt đầu vào tháng Chín.', category: 'Các tháng' },
      { id: 'u9_v7', word: 'October', phonetic: '/ɒkˈtəʊ.bər/', meaningVi: 'tháng Mười', partOfSpeech: 'n', exampleEn: 'Our sports day is in October.', exampleVi: 'Ngày hội thể thao vào tháng Mười.', category: 'Các tháng' },
      { id: 'u9_v8', word: 'November', phonetic: '/nəʊˈvem.bər/', meaningVi: 'tháng Mười Một', partOfSpeech: 'n', exampleEn: 'It is in November.', exampleVi: 'Nó diễn ra vào tháng Mười Một.', category: 'Các tháng' },
      { id: 'u9_v9', word: 'December', phonetic: '/dɪˈsem.bər/', meaningVi: 'tháng Mười Hai', partOfSpeech: 'n', exampleEn: 'Christmas is in December.', exampleVi: 'Giáng sinh vào tháng Mười Hai.', category: 'Các tháng' },
    ],
    extendedVocab: [
      { id: 'u9_ev1', word: 'medal', phonetic: '/ˈmed.əl/', meaningVi: 'huy chương', partOfSpeech: 'n', exampleEn: 'He won a gold medal.', exampleVi: 'Cậu ấy đã giành huy chương vàng.', isExtended: true, category: 'Mở rộng: Thể thao' },
      { id: 'u9_ev2', word: 'trophy', phonetic: '/ˈtrəʊ.fi/', meaningVi: 'chiếc cúp vô địch', partOfSpeech: 'n', exampleEn: 'Our class won the championship trophy.', exampleVi: 'Lớp mình đã giành cúp vô địch.', isExtended: true, category: 'Mở rộng: Thể thao' },
      { id: 'u9_ev3', word: 'tug of war', phonetic: '/ˌtʌɡ əv ˈwɔːr/', meaningVi: 'trò chơi kéo co', partOfSpeech: 'n', exampleEn: 'We play tug of war on sports day.', exampleVi: 'Chúng tớ chơi kéo co trong ngày hội thể thao.', isExtended: true, category: 'Mở rộng: Trò chơi' },
      { id: 'u9_ev4', word: 'relay race', phonetic: '/ˈriː.leɪ reɪs/', meaningVi: 'chạy tiếp sức', partOfSpeech: 'n', exampleEn: 'The relay race is very exciting.', exampleVi: 'Cuộc thi chạy tiếp sức rất hào hứng.', isExtended: true, category: 'Mở rộng: Thể thao' },
    ],
    communication: [
      {
        id: 'u9_c1',
        type: 'answer_to_question',
        instruction: 'Cho câu trả lời, hãy chọn câu hỏi tương ứng:',
        givenLabel: 'Câu trả lời của bạn Mai:',
        prompt: 'Yes, it is. It is in May.',
        targetLabel: 'Câu hỏi của bạn Nam là:',
        options: [
          'Is your sports day in May?',
          'What time do you get up?',
          'Where is your school?',
          'Can you play the guitar?',
        ],
        correctIndex: 0,
        explanation: 'Mai xác nhận "Yes, it is. It is in May", câu hỏi dạng đảo ngữ là "Is your sports day in May?".',
      },
      {
        id: 'u9_c2',
        type: 'answer_to_question',
        instruction: 'Cho câu trả lời, hãy chọn câu hỏi đúng:',
        givenLabel: 'Câu trả lời của bạn Bill:',
        prompt: "It's in October.",
        targetLabel: 'Câu hỏi của bạn Lucy là:',
        options: [
          "When's your sports day?",
          'What day is it today?',
          'What subjects do you have?',
          'Where are you from?',
        ],
        correctIndex: 0,
        explanation: 'Trả lời thời điểm "It\'s in October", câu hỏi là "When\'s your sports day?".',
      },
    ],
    phonics: [
      {
        id: 'u9_ph1',
        letterSound: 'y',
        word: 'February',
        phonetic: '/ˈfeb.ru.ə.ri/',
        sentence: 'Our sports day is in February.',
        translation: 'Ngày hội thể thao trường mình vào tháng Hai.',
        tip: 'Chữ cái "y" ở cuối từ February đọc là âm /i/ ngắn, dứt khoát.',
      },
      {
        id: 'u9_ph2',
        letterSound: 'y',
        word: 'July',
        phonetic: '/dʒuˈlaɪ/',
        sentence: 'My birthday is in July.',
        translation: 'Sinh nhật của mình vào tháng Bảy.',
        tip: 'Chữ cái "y" ở cuối từ July đọc là nguyên âm đôi /aɪ/.',
      },
    ],
    reading: {
      id: 'u9_r1',
      title: 'Our School Sports Day (Trang 67 - SGK)',
      unitId: 9,
      imageTheme: 'sports_field',
      passageEn: 'Our sports day is in November. It is in the school playground. There are many pupils and teachers. We play different sports and games. The boys play badminton. The girls play football. The teachers play basketball. It is a lot of fun!',
      passageVi: 'Ngày hội thể thao trường chúng mình vào tháng Mười Một. Nó diễn ra ở sân chơi của trường. Có rất nhiều học sinh và thầy cô giáo. Chúng mình chơi nhiều môn thể thao và trò chơi khác nhau. Các bạn nam chơi cầu lông. Các bạn nữ chơi bóng đá. Các thầy cô chơi bóng rổ. Thật là nhiều niềm vui!',
      questions: [
        {
          id: 'u9_rq1',
          question: 'When is the sports day? (Ngày hội thể thao diễn ra khi nào?)',
          options: ['In May', 'In November', 'In August', 'In January'],
          correctIndex: 1,
          explanation: 'Trong bài viết: "Our sports day is in November."',
        },
        {
          id: 'u9_rq2',
          question: 'Where is the sports day held? (Ngày hội diễn ra ở đâu?)',
          options: ['In the classroom', 'In the school gym', 'In the school playground', 'At the beach'],
          correctIndex: 2,
          explanation: 'Trong bài: "It is in the school playground."',
        },
        {
          id: 'u9_rq3',
          question: 'What do the boys play? (Các bạn nam chơi môn gì?)',
          options: ['Football', 'Badminton', 'Basketball', 'Tennis'],
          correctIndex: 1,
          explanation: 'Trong bài: "The boys play badminton."',
        },
        {
          id: 'u9_rq4',
          question: 'What do the teachers play? (Thầy cô giáo chơi môn gì?)',
          options: ['Badminton', 'Football', 'Basketball', 'Volleyball'],
          correctIndex: 2,
          explanation: 'Trong bài: "The teachers play basketball."',
        },
      ],
    },
  },
  {
    id: 10,
    title: 'Unit 10: Our Summer Holidays',
    subtitleVi: 'Kỳ nghỉ hè tuyệt vời & Quá khứ đơn was / were',
    themeColor: 'from-violet-600 to-indigo-900',
    icon: '🏖️',
    grammar: [
      {
        id: 'u10_g1',
        title: 'Hỏi cuối tuần trước bạn có ở đâu không (Were you ... last weekend?)',
        pattern: 'Were you in / at / on + [địa điểm] last weekend? - Yes, I was. / No, I wasn\'t. I was in / at / on + [địa điểm].',
        explanation: 'Dùng thì quá khứ đơn (were/was) để hỏi về nơi chốn ai đó đã ở vào cuối tuần trước.',
        examples: [
          { q: 'Were you at the zoo last weekend?', a: 'Yes, I was.', meaning: 'Cuối tuần trước bạn có ở sở thú không? - Đúng vậy, mình đã ở đó.' },
          { q: 'Were you on the beach last weekend?', a: "No, I wasn't. I was in the mountains.", meaning: 'Cuối tuần trước bạn có ở bãi biển không? - Không, mình đã ở vùng núi.' },
        ],
        zeraTip: '💡 Với chủ ngữ "You", dùng "Were you...?". Trả lời với "I", dùng "Yes, I was" hoặc "No, I wasn\'t"!',
      },
      {
        id: 'u10_g2',
        title: 'Hỏi mùa hè trước bạn đã ở đâu (Where were you last summer?)',
        pattern: 'Where were you last summer? - I was in + [Thành phố / Đất nước].',
        explanation: 'Dùng để hỏi một người bạn đã đi du lịch ở đâu vào mùa hè vừa qua.',
        examples: [
          { q: 'Where were you last summer?', a: 'I was in Tokyo.', meaning: 'Mùa hè trước bạn đã ở đâu? - Mình đã ở Tô-ki-ô (Nhật Bản).' },
          { q: 'Where were you last summer?', a: 'I was in London.', meaning: 'Mùa hè trước bạn đã ở đâu? - Mình đã ở Luân Đôn (Anh).' },
        ],
        zeraTip: '💡 Chú ý giới từ: in London / Tokyo (thành phố), at the campsite / zoo (địa điểm), on the beach (bãi biển)!',
      },
    ],
    coreVocab: [
      { id: 'u10_v1', word: 'beach', phonetic: '/biːtʃ/', meaningVi: 'bãi biển', partOfSpeech: 'n', exampleEn: 'I was on the beach last weekend.', exampleVi: 'Tớ đã ở bãi biển vào cuối tuần trước.', category: 'Địa điểm' },
      { id: 'u10_v2', word: 'campsite', phonetic: '/ˈkæmp.saɪt/', meaningVi: 'địa điểm cắm trại', partOfSpeech: 'n', exampleEn: 'We were at the campsite.', exampleVi: 'Chúng tớ đã ở khu cắm trại.', category: 'Địa điểm' },
      { id: 'u10_v3', word: 'countryside', phonetic: '/ˈkʌn.tri.saɪd/', meaningVi: 'vùng quê, nông thôn', partOfSpeech: 'n', exampleEn: 'I was in the countryside.', exampleVi: 'Tớ đã ở vùng quê.', category: 'Địa điểm' },
      { id: 'u10_v4', word: 'zoo', phonetic: '/zuː/', meaningVi: 'sở thú', partOfSpeech: 'n', exampleEn: 'I was at the zoo yesterday.', exampleVi: 'Hôm qua tớ đã ở sở thú.', category: 'Địa điểm' },
      { id: 'u10_v5', word: 'London', phonetic: '/ˈlʌn.dən/', meaningVi: 'thành phố Luân Đôn (Anh)', partOfSpeech: 'n', exampleEn: 'She was in London last summer.', exampleVi: 'Cô ấy đã ở Luân Đôn mùa hè trước.', category: 'Thành phố' },
      { id: 'u10_v6', word: 'Sydney', phonetic: '/ˈsɪd.ni/', meaningVi: 'thành phố Xít-ni (Úc)', partOfSpeech: 'n', exampleEn: 'I was in Sydney.', exampleVi: 'Tớ đã ở Sydney.', category: 'Thành phố' },
      { id: 'u10_v7', word: 'Tokyo', phonetic: '/ˈtəʊ.ki.əʊ/', meaningVi: 'thành phố Tô-ki-ô (Nhật Bản)', partOfSpeech: 'n', exampleEn: 'He was in Tokyo.', exampleVi: 'Cậu ấy đã ở Tokyo.', category: 'Thành phố' },
      { id: 'u10_v8', word: 'Bangkok', phonetic: '/bæŋˈkɒk/', meaningVi: 'thành phố Băng Cốc (Thái Lan)', partOfSpeech: 'n', exampleEn: 'They were in Bangkok.', exampleVi: 'Họ đã ở Bangkok.', category: 'Thành phố' },
      { id: 'u10_v9', word: 'yesterday', phonetic: '/ˈjes.tə.deɪ/', meaningVi: 'ngày hôm qua', partOfSpeech: 'adv', exampleEn: 'I was at home yesterday.', exampleVi: 'Hôm qua tớ đã ở nhà.', category: 'Thời gian' },
    ],
    extendedVocab: [
      { id: 'u10_ev1', word: 'Ha Long Bay', phonetic: '/hɑː lɒŋ beɪ/', meaningVi: 'Vịnh Hạ Long', partOfSpeech: 'n', exampleEn: 'Tony was in Ha Long Bay last summer.', exampleVi: 'Tony đã ở Vịnh Hạ Long mùa hè trước.', isExtended: true, category: 'Mở rộng: Du lịch' },
      { id: 'u10_ev2', word: 'Nha Trang', phonetic: '/ɲaː ʈaːŋ/', meaningVi: 'thành phố biển Nha Trang', partOfSpeech: 'n', exampleEn: 'I was on holiday in Nha Trang.', exampleVi: 'Tớ đi nghỉ mát ở Nha Trang.', isExtended: true, category: 'Mở rộng: Du lịch' },
      { id: 'u10_ev3', word: 'wonderful', phonetic: '/ˈwʌn.də.fəl/', meaningVi: 'tuyệt vời, kỳ diệu', partOfSpeech: 'adj', exampleEn: 'Our summer holiday was wonderful!', exampleVi: 'Kỳ nghỉ hè của chúng mình thật tuyệt vời!', isExtended: true, category: 'Mở rộng: Cảm xúc' },
      { id: 'u10_ev4', word: 'delicious food', phonetic: '/dɪˈlɪʃ.əs fuːd/', meaningVi: 'đồ ăn ngon tuyệt', partOfSpeech: 'phrase', exampleEn: 'The seafood was delicious.', exampleVi: 'Hải sản ngon tuyệt cú mèo.', isExtended: true, category: 'Mở rộng: Ẩm thực' },
    ],
    communication: [
      {
        id: 'u10_c1',
        type: 'answer_to_question',
        instruction: 'Cho câu trả lời, hãy chọn câu hỏi tương ứng:',
        givenLabel: 'Câu trả lời của bạn Mary:',
        prompt: 'No, I wasn’t. I was in the mountains.',
        targetLabel: 'Câu hỏi của bạn Bill là:',
        options: [
          'Were you in the countryside last weekend?',
          'What time do you get up?',
          'Where are you from?',
          'What subjects do you have?',
        ],
        correctIndex: 0,
        explanation: 'Mary trả lời phủ định nơi chốn trong quá khứ "No, I wasn\'t...", câu hỏi là "Were you in the countryside last weekend?".',
      },
      {
        id: 'u10_c2',
        type: 'answer_to_question',
        instruction: 'Cho câu trả lời, hãy chọn câu hỏi thích hợp:',
        givenLabel: 'Câu trả lời của bạn Nam:',
        prompt: 'I was in Tokyo.',
        targetLabel: 'Câu hỏi của bạn Mai là:',
        options: [
          'Where were you last summer?',
          'Where are you from?',
          'When is your birthday?',
          'Can you swim?',
        ],
        correctIndex: 0,
        explanation: 'Nam trả lời nơi mình đã đến mùa hè vừa rồi ("I was in Tokyo"), câu hỏi là "Where were you last summer?".',
      },
    ],
    phonics: [
      {
        id: 'u10_ph1',
        letterSound: 'ere',
        word: 'were',
        phonetic: '/wɜːr/',
        sentence: 'Were you on the beach last summer?',
        translation: 'Mùa hè trước bạn đã ở trên bãi biển à?',
        tip: 'Từ "were" phát âm với nguyên âm dài /ɜːr/, tròn khẩu hình miệng.',
      },
      {
        id: 'u10_ph2',
        letterSound: 'ere',
        word: 'where',
        phonetic: '/weər/',
        sentence: 'Where were you last weekend?',
        translation: 'Cuối tuần trước bạn đã ở đâu?',
        tip: 'Từ "where" phát âm với nguyên âm đôi /eər/. Chú ý phân biệt were /wɜːr/ và where /weər/ nhé!',
      },
    ],
    reading: {
      id: 'u10_r1',
      title: "Mai in London and Tony in Ha Long Bay (Trang 73 - SGK)",
      unitId: 10,
      imageTheme: 'summer_holiday',
      passageEn: 'I am Mai. Last summer, I was on holiday in London. The city was busy. The food was good. The people were helpful. My holiday was great! --- My name is Tony. I was on holiday in Ha Long Bay last summer. The bay was beautiful. The food was excellent. The people were friendly. My holiday was great!',
      passageVi: 'Mình là Mai. Mùa hè năm ngoái, mình đã đi nghỉ ở Luân Đôn. Thành phố rất nhộn nhịp. Đồ ăn rất ngon. Mọi người rất hay giúp đỡ. Kỳ nghỉ của mình thật tuyệt vời! --- Tên mình là Tony. Mùa hè năm ngoái mình đi nghỉ ở Vịnh Hạ Long. Vịnh rất đẹp. Đồ ăn thì xuất sắc. Mọi người rất thân thiện. Kỳ nghỉ của mình thật tuyệt vời!',
      questions: [
        {
          id: 'u10_rq1',
          question: 'Where was Mai last summer? (Mai đã ở đâu vào mùa hè trước?)',
          options: ['In Sydney', 'In London', 'In Ha Long Bay', 'In Tokyo'],
          correctIndex: 1,
          explanation: 'Trong bài viết: "Last summer, I was on holiday in London."',
        },
        {
          id: 'u10_rq2',
          question: 'How was London? (Thành phố Luân Đôn như thế nào?)',
          options: ['It was quiet.', 'It was busy.', 'It was boring.', 'It was hot.'],
          correctIndex: 1,
          explanation: 'Trong bài: "The city was busy."',
        },
        {
          id: 'u10_rq3',
          question: 'Where was Tony on holiday? (Tony đã đi nghỉ ở đâu?)',
          options: ['London', 'Ha Long Bay', 'Tokyo', 'Bangkok'],
          correctIndex: 1,
          explanation: 'Trong bài: "I was on holiday in Ha Long Bay last summer."',
        },
        {
          id: 'u10_rq4',
          question: 'How were the people in Ha Long Bay? (Người dân ở Vịnh Hạ Long như thế nào?)',
          options: ['They were busy.', 'They were quiet.', 'They were friendly.', 'They were tired.'],
          correctIndex: 2,
          explanation: 'Trong bài: "The people were friendly."',
        },
      ],
    },
  },
];
